const BASE = 'https://raw.githubusercontent.com/Tarikul-Islam-Anik/Telegram-Animated-Emojis/main'

export const EMOJI_MAP: Record<string, { name: string; path: string }> = {
  '👍': { name: 'Thumbs Up', path: 'People/Thumbs%20Up.webp' },
  '❤️': { name: 'Red Heart', path: 'Symbols/Red%20Heart.webp' },
  '😂': { name: 'Face With Tears Of Joy', path: 'Smileys/Face%20With%20Tears%20Of%20Joy.webp' },
  '😮': { name: 'Face With Open Mouth', path: 'Smileys/Face%20With%20Open%20Mouth.webp' },
  '😢': { name: 'Crying Face', path: 'Smileys/Crying%20Face.webp' },
  '🔥': { name: 'Fire', path: 'Animals%20and%20Nature/Fire.webp' },
  '🎉': { name: 'Party Popper', path: 'Activity/Party%20Popper.webp' },
  '👏': { name: 'Clapping Hands', path: 'People/Clapping%20Hands.webp' },
  '🤔': { name: 'Thinking Face', path: 'Smileys/Thinking%20Face.webp' },
  '😎': { name: 'Smiling Face With Sunglasses', path: 'Smileys/Smiling%20Face%20With%20Sunglasses.webp' },
  '🥳': { name: 'Partying Face', path: 'Smileys/Partying%20Face.webp' },
  '😱': { name: 'Face Screaming In Fear', path: 'Smileys/Face%20Screaming%20In%20Fear.webp' },
}

export const QUICK_EMOJIS = Object.keys(EMOJI_MAP)

export function emojiUrl(emoji: string): string {
  const info = EMOJI_MAP[emoji]
  if (!info) return ''
  return `${BASE}/${info.path}`
}

interface EmojiItem {
  char: string
  name: string
  path: string
}

const CATEGORIES: Record<string, EmojiItem[]> = {
  'ยิ้ม': [
    { char: '😀', name: 'Grinning Face', path: 'Smileys/Grinning%20Face.webp' },
    { char: '😃', name: 'Grinning Face With Big Eyes', path: 'Smileys/Grinning%20Face%20With%20Big%20Eyes.webp' },
    { char: '😄', name: 'Grinning Face With Smiling Eyes', path: 'Smileys/Grinning%20Face%20With%20Smiling%20Eyes.webp' },
    { char: '😁', name: 'Beaming Face With Smiling Eyes', path: 'Smileys/Beaming%20Face%20With%20Smiling%20Eyes.webp' },
    { char: '😆', name: 'Grinning Squinting Face', path: 'Smileys/Grinning%20Squinting%20Face.webp' },
    { char: '😅', name: 'Grinning Face With Sweat', path: 'Smileys/Grinning%20Face%20With%20Sweat.webp' },
    { char: '🤣', name: 'Rolling On The Floor Laughing', path: 'Smileys/Rolling%20On%20The%20Floor%20Laughing.webp' },
    { char: '😂', name: 'Face With Tears Of Joy', path: 'Smileys/Face%20With%20Tears%20Of%20Joy.webp' },
    { char: '🙂', name: 'Slightly Smiling Face', path: 'Smileys/Slightly%20Smiling%20Face.webp' },
    { char: '😉', name: 'Winking Face', path: 'Smileys/Winking%20Face.webp' },
    { char: '😊', name: 'Smiling Face With Smiling Eyes', path: 'Smileys/Smiling%20Face%20With%20Smiling%20Eyes.webp' },
    { char: '😍', name: 'Smiling Face With Heart Eyes', path: 'Smileys/Smiling%20Face%20With%20Heart%20Eyes.webp' },
    { char: '🥰', name: 'Smiling Face With Hearts', path: 'Smileys/Smiling%20Face%20With%20Hearts.webp' },
    { char: '😘', name: 'Face Blowing A Kiss', path: 'Smileys/Face%20Blowing%20A%20Kiss.webp' },
    { char: '😎', name: 'Smiling Face With Sunglasses', path: 'Smileys/Smiling%20Face%20With%20Sunglasses.webp' },
    { char: '🤩', name: 'Star Struck', path: 'Smileys/Star%20Struck.webp' },
    { char: '🥳', name: 'Partying Face', path: 'Smileys/Partying%20Face.webp' },
    { char: '😏', name: 'Smirking Face', path: 'Smileys/Smirking%20Face.webp' },
    { char: '😒', name: 'Unamused Face', path: 'Smileys/Unamused%20Face.webp' },
    { char: '🙄', name: 'Face With Rolling Eyes', path: 'Smileys/Face%20With%20Rolling%20Eyes.webp' },
    { char: '😴', name: 'Sleeping Face', path: 'Smileys/Sleeping%20Face.webp' },
    { char: '🤔', name: 'Thinking Face', path: 'Smileys/Thinking%20Face.webp' },
    { char: '🤨', name: 'Face With Raised Eyebrow', path: 'Smileys/Face%20With%20Raised%20Eyebrow.webp' },
    { char: '😐', name: 'Neutral Face', path: 'Smileys/Neutral%20Face.webp' },
  ],
  'อารมณ์': [
    { char: '😢', name: 'Crying Face', path: 'Smileys/Crying%20Face.webp' },
    { char: '😭', name: 'Loudly Crying Face', path: 'Smileys/Loudly%20Crying%20Face.webp' },
    { char: '😠', name: 'Angry Face', path: 'Smileys/Angry%20Face.webp' },
    { char: '😡', name: 'Pouting Face', path: 'Smileys/Pouting%20Face.webp' },
    { char: '🤬', name: 'Face With Symbols On Mouth', path: 'Smileys/Face%20With%20Symbols%20On%20Mouth.webp' },
    { char: '😱', name: 'Face Screaming In Fear', path: 'Smileys/Face%20Screaming%20In%20Fear.webp' },
    { char: '😨', name: 'Fearful Face', path: 'Smileys/Fearful%20Face.webp' },
    { char: '😰', name: 'Anxious Face With Sweat', path: 'Smileys/Anxious%20Face%20With%20Sweat.webp' },
    { char: '😥', name: 'Sad But Relieved Face', path: 'Smileys/Sad%20But%20Relieved%20Face.webp' },
    { char: '😓', name: 'Downcast Face With Sweat', path: 'Smileys/Downcast%20Face%20With%20Sweat.webp' },
    { char: '🤗', name: 'Smiling Face With Open Hands', path: 'Smileys/Smiling%20Face%20With%20Open%20Hands.webp' },
    { char: '🤭', name: 'Face With Hand Over Mouth', path: 'Smileys/Face%20With%20Hand%20Over%20Mouth.webp' },
    { char: '🤫', name: 'Shushing Face', path: 'Smileys/Shushing%20Face.webp' },
    { char: '🤥', name: 'Lying Face', path: 'Smileys/Lying%20Face.webp' },
    { char: '🙄', name: 'Face With Rolling Eyes', path: 'Smileys/Face%20With%20Rolling%20Eyes.webp' },
    { char: '😬', name: 'Grimacing Face', path: 'Smileys/Grimacing%20Face.webp' },
    { char: '🥱', name: 'Yawning Face', path: 'Smileys/Yawning%20Face.webp' },
    { char: '🤤', name: 'Drooling Face', path: 'Smileys/Drooling%20Face.webp' },
    { char: '😮', name: 'Face With Open Mouth', path: 'Smileys/Face%20With%20Open%20Mouth.webp' },
    { char: '😯', name: 'Hushed Face', path: 'Smileys/Hushed%20Face.webp' },
    { char: '😵', name: 'Face With Crossed Out Eyes', path: 'Smileys/Face%20With%20Crossed%20Out%20Eyes.webp' },
    { char: '🤯', name: 'Exploding Head', path: 'Smileys/Exploding%20Head.webp' },
    { char: '🥶', name: 'Freezing Face', path: 'Smileys/Freezing%20Face.webp' },
    { char: '🥵', name: 'Hot Face', path: 'Smileys/Hot%20Face.webp' },
  ],
  'ท่าทาง': [
    { char: '👍', name: 'Thumbs Up', path: 'People/Thumbs%20Up.webp' },
    { char: '👎', name: 'Thumbs Down', path: 'People/Thumbs%20Down.webp' },
    { char: '👌', name: 'OK Hand', path: 'People/OK%20Hand.webp' },
    { char: '🤌', name: 'Pinched Fingers', path: 'People/Pinched%20Fingers.webp' },
    { char: '🤏', name: 'Pinching Hand', path: 'People/Pinching%20Hand.webp' },
    { char: '✌️', name: 'Victory Hand', path: 'People/Victory%20Hand.webp' },
    { char: '🤞', name: 'Crossed Fingers', path: 'People/Crossed%20Fingers.webp' },
    { char: '🤟', name: 'Love You Gesture', path: 'People/Love%20You%20Gesture.webp' },
    { char: '🤘', name: 'Sign Of The Horns', path: 'People/Sign%20Of%20The%20Horns.webp' },
    { char: '🤙', name: 'Call Me Hand', path: 'People/Call%20Me%20Hand.webp' },
    { char: '👈', name: 'Backhand Index Pointing Left', path: 'People/Backhand%20Index%20Pointing%20Left.webp' },
    { char: '👉', name: 'Backhand Index Pointing Right', path: 'People/Backhand%20Index%20Pointing%20Right.webp' },
    { char: '👆', name: 'Backhand Index Pointing Up', path: 'People/Backhand%20Index%20Pointing%20Up.webp' },
    { char: '👇', name: 'Backhand Index Pointing Down', path: 'People/Backhand%20Index%20Pointing%20Down.webp' },
    { char: '☝️', name: 'Index Pointing Up', path: 'People/Index%20Pointing%20Up.webp' },
    { char: '👋', name: 'Waving Hand', path: 'People/Waving%20Hand.webp' },
    { char: '🤚', name: 'Raised Back Of Hand', path: 'People/Raised%20Back%20Of%20Hand.webp' },
    { char: '🖐️', name: 'Hand With Fingers Splayed', path: 'People/Hand%20With%20Fingers%20Splayed.webp' },
    { char: '✋', name: 'Raised Hand', path: 'People/Raised%20Hand.webp' },
    { char: '👏', name: 'Clapping Hands', path: 'People/Clapping%20Hands.webp' },
    { char: '🙌', name: 'Raising Hands', path: 'People/Raising%20Hands.webp' },
    { char: '🤝', name: 'Handshake', path: 'People/Handshake.webp' },
    { char: '🙏', name: 'Folded Hands', path: 'People/Folded%20Hands.webp' },
    { char: '💪', name: 'Flexed Biceps', path: 'People/Flexed%20Biceps.webp' },
  ],
  'หัวใจ': [
    { char: '❤️', name: 'Red Heart', path: 'Symbols/Red%20Heart.webp' },
    { char: '🧡', name: 'Orange Heart', path: 'Symbols/Orange%20Heart.webp' },
    { char: '💛', name: 'Yellow Heart', path: 'Symbols/Yellow%20Heart.webp' },
    { char: '💚', name: 'Green Heart', path: 'Symbols/Green%20Heart.webp' },
    { char: '💙', name: 'Blue Heart', path: 'Symbols/Blue%20Heart.webp' },
    { char: '💜', name: 'Purple Heart', path: 'Symbols/Purple%20Heart.webp' },
    { char: '🖤', name: 'Black Heart', path: 'Symbols/Black%20Heart.webp' },
    { char: '🤍', name: 'White Heart', path: 'Symbols/White%20Heart.webp' },
    { char: '🤎', name: 'Brown Heart', path: 'Symbols/Brown%20Heart.webp' },
    { char: '💔', name: 'Broken Heart', path: 'Symbols/Broken%20Heart.webp' },
    { char: '❣️', name: 'Heart Exclamation', path: 'Symbols/Heart%20Exclamation.webp' },
    { char: '💕', name: 'Two Hearts', path: 'Symbols/Two%20Hearts.webp' },
    { char: '💞', name: 'Revolving Hearts', path: 'Symbols/Revolving%20Hearts.webp' },
    { char: '💓', name: 'Beating Heart', path: 'Symbols/Beating%20Heart.webp' },
    { char: '💗', name: 'Growing Heart', path: 'Symbols/Growing%20Heart.webp' },
    { char: '💖', name: 'Sparkling Heart', path: 'Symbols/Sparkling%20Heart.webp' },
    { char: '💘', name: 'Heart With Arrow', path: 'Symbols/Heart%20With%20Arrow.webp' },
    { char: '💝', name: 'Heart With Ribbon', path: 'Symbols/Heart%20With%20Ribbon.webp' },
    { char: '💟', name: 'Heart Decoration', path: 'Symbols/Heart%20Decoration.webp' },
  ],
  'ธรรมชาติ': [
    { char: '🔥', name: 'Fire', path: 'Animals%20and%20Nature/Fire.webp' },
    { char: '✨', name: 'Sparkles', path: 'Animals%20and%20Nature/Sparkles.webp' },
    { char: '⭐', name: 'Star', path: 'Animals%20and%20Nature/Star.webp' },
    { char: '🌟', name: 'Glowing Star', path: 'Animals%20and%20Nature/Glowing%20Star.webp' },
    { char: '💫', name: 'Dizzy', path: 'Smileys/Dizzy.webp' },
    { char: '🌈', name: 'Rainbow', path: 'Animals%20and%20Nature/Rainbow.webp' },
    { char: '☀️', name: 'Sun', path: 'Animals%20and%20Nature/Sun.webp' },
    { char: '🌙', name: 'Crescent Moon', path: 'Animals%20and%20Nature/Crescent%20Moon.webp' },
    { char: '⚡', name: 'High Voltage', path: 'Animals%20and%20Nature/High%20Voltage.webp' },
    { char: '❄️', name: 'Snowflake', path: 'Animals%20and%20Nature/Snowflake.webp' },
    { char: '🌊', name: 'Water Wave', path: 'Animals%20and%20Nature/Water%20Wave.webp' },
    { char: '🌸', name: 'Cherry Blossom', path: 'Animals%20and%20Nature/Cherry%20Blossom.webp' },
    { char: '🌺', name: 'Hibiscus', path: 'Animals%20and%20Nature/Hibiscus.webp' },
    { char: '🌻', name: 'Sunflower', path: 'Animals%20and%20Nature/Sunflower.webp' },
    { char: '🌹', name: 'Rose', path: 'Animals%20and%20Nature/Rose.webp' },
    { char: '🌷', name: 'Tulip', path: 'Animals%20and%20Nature/Tulip.webp' },
    { char: '💐', name: 'Bouquet', path: 'Animals%20and%20Nature/Bouquet.webp' },
    { char: '🐱', name: 'Cat Face', path: 'Animals%20and%20Nature/Cat%20Face.webp' },
    { char: '🐶', name: 'Dog Face', path: 'Animals%20and%20Nature/Dog%20Face.webp' },
    { char: '🦊', name: 'Fox', path: 'Animals%20and%20Nature/Fox.webp' },
    { char: '🦉', name: 'Owl', path: 'Animals%20and%20Nature/Owl.webp' },
    { char: '🦄', name: 'Unicorn', path: 'Animals%20and%20Nature/Unicorn.webp' },
    { char: '🦋', name: 'Butterfly', path: 'Animals%20and%20Nature/Butterfly.webp' },
    { char: '🐝', name: 'Honeybee', path: 'Animals%20and%20Nature/Honeybee.webp' },
  ],
  'อาหาร': [
    { char: '🍎', name: 'Red Apple', path: 'Food%20and%20Drink/Red%20Apple.webp' },
    { char: '🍊', name: 'Tangerine', path: 'Food%20and%20Drink/Tangerine.webp' },
    { char: '🍋', name: 'Lemon', path: 'Food%20and%20Drink/Lemon.webp' },
    { char: '🍇', name: 'Grapes', path: 'Food%20and%20Drink/Grapes.webp' },
    { char: '🍓', name: 'Strawberry', path: 'Food%20and%20Drink/Strawberry.webp' },
    { char: '🍔', name: 'Hamburger', path: 'Food%20and%20Drink/Hamburger.webp' },
    { char: '🍕', name: 'Pizza', path: 'Food%20and%20Drink/Pizza.webp' },
    { char: '🌭', name: 'Hot Dog', path: 'Food%20and%20Drink/Hot%20Dog.webp' },
    { char: '🥪', name: 'Sandwich', path: 'Food%20and%20Drink/Sandwich.webp' },
    { char: '🌮', name: 'Taco', path: 'Food%20and%20Drink/Taco.webp' },
    { char: '🍜', name: 'Steaming Bowl', path: 'Food%20and%20Drink/Steaming%20Bowl.webp' },
    { char: '🍝', name: 'Spaghetti', path: 'Food%20and%20Drink/Spaghetti.webp' },
    { char: '🍣', name: 'Sushi', path: 'Food%20and%20Drink/Sushi.webp' },
    { char: '🍦', name: 'Soft Ice Cream', path: 'Food%20and%20Drink/Soft%20Ice%20Cream.webp' },
    { char: '🍰', name: 'Shortcake', path: 'Food%20and%20Drink/Shortcake.webp' },
    { char: '🍪', name: 'Cookie', path: 'Food%20and%20Drink/Cookie.webp' },
    { char: '🍫', name: 'Chocolate Bar', path: 'Food%20and%20Drink/Chocolate%20Bar.webp' },
    { char: '🍿', name: 'Popcorn', path: 'Food%20and%20Drink/Popcorn.webp' },
    { char: '☕', name: 'Hot Beverage', path: 'Food%20and%20Drink/Hot%20Beverage.webp' },
    { char: '🍺', name: 'Clinking Beer Mugs', path: 'Food%20and%20Drink/Clinking%20Beer%20Mugs.webp' },
    { char: '🧋', name: 'Bubble Tea', path: 'Food%20and%20Drink/Bubble%20Tea.webp' },
    { char: '🍷', name: 'Wine Glass', path: 'Food%20and%20Drink/Wine%20Glass.webp' },
    { char: '🥂', name: 'Clinking Glasses', path: 'Food%20and%20Drink/Clinking%20Glasses.webp' },
    { char: '🍹', name: 'Tropical Drink', path: 'Food%20and%20Drink/Tropical%20Drink.webp' },
  ],
  'กิจกรรม': [
    { char: '🎉', name: 'Party Popper', path: 'Activity/Party%20Popper.webp' },
    { char: '🎊', name: 'Confetti Ball', path: 'Activity/Confetti%20Ball.webp' },
    { char: '🎈', name: 'Balloon', path: 'Activity/Balloon.webp' },
    { char: '🎂', name: 'Birthday Cake', path: 'Food%20and%20Drink/Birthday%20Cake.webp' },
    { char: '🎁', name: 'Wrapped Gift', path: 'Activity/Wrapped%20Gift.webp' },
    { char: '🎄', name: 'Christmas Tree', path: 'Activity/Christmas%20Tree.webp' },
    { char: '🎃', name: 'Jack O Lantern', path: 'Activity/Jack%20O%20Lantern.webp' },
    { char: '🎆', name: 'Fireworks', path: 'Activity/Fireworks.webp' },
    { char: '🎇', name: 'Sparkler', path: 'Activity/Sparkler.webp' },
    { char: '🎨', name: 'Artist Palette', path: 'Activity/Artist%20Palette.webp' },
    { char: '🎮', name: 'Video Game', path: 'Activity/Video%20Game.webp' },
    { char: '🎯', name: 'Direct Hit', path: 'Activity/Direct%20Hit.webp' },
    { char: '🏆', name: 'Trophy', path: 'Activity/Trophy.webp' },
    { char: '🥇', name: '1st Place Medal', path: 'Activity/1st%20Place%20Medal.webp' },
    { char: '⚽', name: 'Soccer Ball', path: 'Activity/Soccer%20Ball.webp' },
    { char: '🏀', name: 'Basketball', path: 'Activity/Basketball.webp' },
    { char: '🎵', name: 'Musical Note', path: 'Activity/Musical%20Note.webp' },
    { char: '🎶', name: 'Musical Notes', path: 'Activity/Musical%20Notes.webp' },
    { char: '🎤', name: 'Microphone', path: 'Activity/Microphone.webp' },
    { char: '🎸', name: 'Guitar', path: 'Activity/Guitar.webp' },
    { char: '🪕', name: 'Banjo', path: 'Activity/Banjo.webp' },
    { char: '🎲', name: 'Game Die', path: 'Activity/Game%20Die.webp' },
    { char: '🧩', name: 'Puzzle Piece', path: 'Activity/Puzzle%20Piece.webp' },
    { char: '✈️', name: 'Airplane', path: 'Travel%20and%20Places/Airplane.webp' },
  ],
  'สัญลักษณ์': [
    { char: '✅', name: 'Check Mark Button', path: 'Symbols/Check%20Mark%20Button.webp' },
    { char: '❌', name: 'Cross Mark', path: 'Symbols/Cross%20Mark.webp' },
    { char: '❎', name: 'Cross Mark Button', path: 'Symbols/Cross%20Mark%20Button.webp' },
    { char: '💯', name: 'Hundred Points', path: 'Symbols/Hundred%20Points.webp' },
    { char: '🔔', name: 'Bell', path: 'Objects/Bell.webp' },
    { char: '🔕', name: 'Bell With Slash', path: 'Objects/Bell%20With%20Slash.webp' },
    { char: '📢', name: 'Loudspeaker', path: 'Objects/Loudspeaker.webp' },
    { char: '💬', name: 'Speech Balloon', path: 'Objects/Speech%20Balloon.webp' },
    { char: '💭', name: 'Thought Balloon', path: 'Objects/Thought%20Balloon.webp' },
    { char: '⏰', name: 'Alarm Clock', path: 'Objects/Alarm%20Clock.webp' },
    { char: '💡', name: 'Light Bulb', path: 'Objects/Light%20Bulb.webp' },
    { char: '📌', name: 'Pushpin', path: 'Objects/Pushpin.webp' },
    { char: '📍', name: 'Round Pushpin', path: 'Objects/Round%20Pushpin.webp' },
    { char: '🚀', name: 'Rocket', path: 'Travel%20and%20Places/Rocket.webp' },
    { char: '🛸', name: 'Flying Saucer', path: 'Travel%20and%20Places/Flying%20Saucer.webp' },
    { char: '🌍', name: 'Globe Showing Europe Africa', path: 'Travel%20and%20Places/Globe%20Showing%20Europe%20Africa.webp' },
    { char: '🌙', name: 'Crescent Moon', path: 'Animals%20and%20Nature/Crescent%20Moon.webp' },
    { char: '⚡', name: 'High Voltage', path: 'Animals%20and%20Nature/High%20Voltage.webp' },
    { char: '💦', name: 'Sweat Droplets', path: 'Animals%20and%20Nature/Sweat%20Droplets.webp' },
    { char: '💨', name: 'Dashing Away', path: 'Animals%20and%20Nature/Dashing%20Away.webp' },
    { char: '🕳️', name: 'Hole', path: 'Animals%20and%20Nature/Hole.webp' },
    { char: '💣', name: 'Bomb', path: 'Objects/Bomb.webp' },
    { char: '💤', name: 'Zzz', path: 'Smileys/Zzz.webp' },
    { char: '🎉', name: 'Party Popper', path: 'Activity/Party%20Popper.webp' },
  ],
}

export const EMOJI_CATEGORIES = CATEGORIES
export const EMOJI_CATEGORY_NAMES = Object.keys(CATEGORIES)

const ALL_EMOJIS: EmojiItem[] = Object.values(CATEGORIES).flat()
const EMOJI_BY_CHAR = new Map<string, EmojiItem>(ALL_EMOJIS.map((e) => [e.char, e]))

export function emojiUrlFromChar(char: string): string {
  const item = EMOJI_BY_CHAR.get(char)
  if (item) return `${BASE}/${item.path}`
  const info = EMOJI_MAP[char]
  if (info) return `${BASE}/${info.path}`
  return ''
}

export const AVATAR_EMOJIS = ALL_EMOJIS.map((e) => e.char)
