// ponytail: GitHub animated Fluent emojis (APNG, ~800KB each but CDN-cached)
const BASE = 'https://raw.githubusercontent.com/Tarikul-Islam-Anik/Animated-Fluent-Emojis/master/Emojis'

export const EMOJI_MAP: Record<string, { name: string; path: string }> = {
  '👍': { name: 'Thumbs Up', path: 'Hand%20gestures/Thumbs%20Up.png' },
  '❤️': { name: 'Red Heart', path: 'Smilies/Red%20Heart.png' },
  '😂': { name: 'Face With Tears Of Joy', path: 'Smilies/Face%20with%20Tears%20of%20Joy.png' },
  '😮': { name: 'Face With Open Mouth', path: 'Smilies/Face%20with%20Open%20Mouth.png' },
  '😢': { name: 'Crying Face', path: 'Smilies/Crying%20Face.png' },
  '🔥': { name: 'Fire', path: 'Travel%20and%20places/Fire.png' },
  '🎉': { name: 'Party Popper', path: 'Activities/Party%20Popper.png' },
  '👏': { name: 'Clapping Hands', path: 'Hand%20gestures/Clapping%20Hands.png' },
  '🤔': { name: 'Thinking Face', path: 'Smilies/Thinking%20Face.png' },
  '😎': { name: 'Smiling Face With Sunglasses', path: 'Smilies/Smiling%20Face%20with%20Sunglasses.png' },
  '🥳': { name: 'Partying Face', path: 'Smilies/Partying%20Face.png' },
  '😱': { name: 'Face Screaming In Fear', path: 'Smilies/Face%20Screaming%20in%20Fear.png' },
}

export const QUICK_EMOJIS = Object.keys(EMOJI_MAP)

export function emojiUrl(emoji: string): string {
  const info = EMOJI_MAP[emoji]
  if (!info) return ''
  return `${BASE}/${info.path}`
}

interface EmojiItem {
  char: string
  name: string
  path: string
}

const CATEGORIES: Record<string, EmojiItem[]> = {
  'ยิ้ม': [
    { char: '😀', name: 'Grinning Face', path: 'Smilies/Grinning%20Face.png' },
    { char: '😃', name: 'Grinning Face With Big Eyes', path: 'Smilies/Grinning%20Face%20with%20Big%20Eyes.png' },
    { char: '😄', name: 'Grinning Face With Smiling Eyes', path: 'Smilies/Grinning%20Face%20with%20Smiling%20Eyes.png' },
    { char: '😁', name: 'Beaming Face With Smiling Eyes', path: 'Smilies/Beaming%20Face%20with%20Smiling%20Eyes.png' },
    { char: '😆', name: 'Grinning Squinting Face', path: 'Smilies/Grinning%20Squinting%20Face.png' },
    { char: '😅', name: 'Grinning Face With Sweat', path: 'Smilies/Grinning%20Face%20with%20Sweat.png' },
    { char: '🤣', name: 'Rolling On The Floor Laughing', path: 'Smilies/Rolling%20on%20the%20Floor%20Laughing.png' },
    { char: '😂', name: 'Face With Tears Of Joy', path: 'Smilies/Face%20with%20Tears%20of%20Joy.png' },
    { char: '🙂', name: 'Slightly Smiling Face', path: 'Smilies/Slightly%20Smiling%20Face.png' },
    { char: '😉', name: 'Winking Face', path: 'Smilies/Winking%20Face.png' },
    { char: '😊', name: 'Smiling Face With Smiling Eyes', path: 'Smilies/Smiling%20Face%20with%20Smiling%20Eyes.png' },
    { char: '😍', name: 'Smiling Face With Heart Eyes', path: 'Smilies/Smiling%20Face%20with%20Heart-Eyes.png' },
    { char: '🥰', name: 'Smiling Face With Hearts', path: 'Smilies/Smiling%20Face%20with%20Hearts.png' },
    { char: '😘', name: 'Face Blowing A Kiss', path: 'Smilies/Face%20Blowing%20a%20Kiss.png' },
    { char: '😎', name: 'Smiling Face With Sunglasses', path: 'Smilies/Smiling%20Face%20with%20Sunglasses.png' },
    { char: '🤩', name: 'Star Struck', path: 'Smilies/Star-Struck.png' },
    { char: '🥳', name: 'Partying Face', path: 'Smilies/Partying%20Face.png' },
    { char: '😏', name: 'Smirking Face', path: 'Smilies/Smirking%20Face.png' },
    { char: '😒', name: 'Unamused Face', path: 'Smilies/Unamused%20Face.png' },
    { char: '🙄', name: 'Face With Rolling Eyes', path: 'Smilies/Face%20with%20Rolling%20Eyes.png' },
    { char: '😴', name: 'Sleeping Face', path: 'Smilies/Sleeping%20Face.png' },
    { char: '🤔', name: 'Thinking Face', path: 'Smilies/Thinking%20Face.png' },
    { char: '🤨', name: 'Face With Raised Eyebrow', path: 'Smilies/Face%20with%20Raised%20Eyebrow.png' },
    { char: '😐', name: 'Neutral Face', path: 'Smilies/Neutral%20Face.png' },
  ],
  'อารมณ์': [
    { char: '😢', name: 'Crying Face', path: 'Smilies/Crying%20Face.png' },
    { char: '😭', name: 'Loudly Crying Face', path: 'Smilies/Loudly%20Crying%20Face.png' },
    { char: '😠', name: 'Angry Face', path: 'Smilies/Angry%20Face.png' },
    { char: '😡', name: 'Pouting Face', path: 'Smilies/Pouting%20Cat.png' },
    { char: '🤬', name: 'Face With Symbols On Mouth', path: 'Smilies/Face%20with%20Symbols%20on%20Mouth.png' },
    { char: '😱', name: 'Face Screaming In Fear', path: 'Smilies/Face%20Screaming%20in%20Fear.png' },
    { char: '😨', name: 'Fearful Face', path: 'Smilies/Fearful%20Face.png' },
    { char: '😰', name: 'Anxious Face With Sweat', path: 'Smilies/Anxious%20Face%20with%20Sweat.png' },
    { char: '😥', name: 'Sad But Relieved Face', path: 'Smilies/Sad%20but%20Relieved%20Face.png' },
    { char: '😓', name: 'Downcast Face With Sweat', path: 'Smilies/Downcast%20Face%20with%20Sweat.png' },
    { char: '🤗', name: 'Smiling Face With Open Hands', path: 'Smilies/Smiling%20Face%20with%20Open%20Hands.png' },
    { char: '🤭', name: 'Face With Hand Over Mouth', path: 'Smilies/Face%20with%20Hand%20Over%20Mouth.png' },
    { char: '🤫', name: 'Shushing Face', path: 'Smilies/Shushing%20Face.png' },
    { char: '🤥', name: 'Lying Face', path: 'Smilies/Lying%20Face.png' },
    { char: '🙄', name: 'Face With Rolling Eyes', path: 'Smilies/Face%20with%20Rolling%20Eyes.png' },
    { char: '😬', name: 'Grimacing Face', path: 'Smilies/Grimacing%20Face.png' },
    { char: '🥱', name: 'Yawning Face', path: 'Smilies/Yawning%20Face.png' },
    { char: '🤤', name: 'Drooling Face', path: 'Smilies/Drooling%20Face.png' },
    { char: '😮', name: 'Face With Open Mouth', path: 'Smilies/Face%20with%20Open%20Mouth.png' },
    { char: '😯', name: 'Hushed Face', path: 'Smilies/Hushed%20Face.png' },
    { char: '😵', name: 'Face With Crossed Out Eyes', path: 'Smilies/Face%20with%20Crossed-Out%20Eyes.png' },
    { char: '🤯', name: 'Exploding Head', path: 'Smilies/Exploding%20Head.png' },
    { char: '🥶', name: 'Freezing Face', path: 'Smilies/Cold%20Face.png' },
    { char: '🥵', name: 'Hot Face', path: 'Smilies/Hot%20Face.png' },
  ],
  'ท่าทาง': [
    { char: '👍', name: 'Thumbs Up', path: 'Hand%20gestures/Thumbs%20Up.png' },
    { char: '👎', name: 'Thumbs Down', path: 'Hand%20gestures/Thumbs%20Down.png' },
    { char: '👌', name: 'OK Hand', path: 'Hand%20gestures/OK%20Hand.png' },
    { char: '🤌', name: 'Pinched Fingers', path: 'Hand%20gestures/Pinched%20Fingers.png' },
    { char: '🤏', name: 'Pinching Hand', path: 'Hand%20gestures/Pinching%20Hand.png' },
    { char: '✌️', name: 'Victory Hand', path: 'Hand%20gestures/Victory%20Hand.png' },
    { char: '🤞', name: 'Crossed Fingers', path: 'Hand%20gestures/Crossed%20Fingers.png' },
    { char: '🤟', name: 'Love You Gesture', path: 'Hand%20gestures/Love-You%20Gesture.png' },
    { char: '🤘', name: 'Sign Of The Horns', path: 'Hand%20gestures/Sign%20of%20the%20Horns.png' },
    { char: '🤙', name: 'Call Me Hand', path: 'Hand%20gestures/Call%20Me%20Hand.png' },
    { char: '👈', name: 'Backhand Index Pointing Left', path: 'Hand%20gestures/Backhand%20Index%20Pointing%20Left.png' },
    { char: '👉', name: 'Backhand Index Pointing Right', path: 'Hand%20gestures/Backhand%20Index%20Pointing%20Right.png' },
    { char: '👆', name: 'Backhand Index Pointing Up', path: 'Hand%20gestures/Backhand%20Index%20Pointing%20Up.png' },
    { char: '👇', name: 'Backhand Index Pointing Down', path: 'Hand%20gestures/Backhand%20Index%20Pointing%20Down.png' },
    { char: '☝️', name: 'Index Pointing Up', path: 'Hand%20gestures/Index%20Pointing%20Up.png' },
    { char: '👋', name: 'Waving Hand', path: 'Hand%20gestures/Waving%20Hand.png' },
    { char: '🤚', name: 'Raised Back Of Hand', path: 'Hand%20gestures/Raised%20Back%20of%20Hand.png' },
    { char: '🖐️', name: 'Hand With Fingers Splayed', path: 'Hand%20gestures/Hand%20with%20Fingers%20Splayed.png' },
    { char: '✋', name: 'Raised Hand', path: 'Hand%20gestures/Raised%20Hand.png' },
    { char: '👏', name: 'Clapping Hands', path: 'Hand%20gestures/Clapping%20Hands.png' },
    { char: '🙌', name: 'Raising Hands', path: 'Hand%20gestures/Raising%20Hands.png' },
    { char: '🤝', name: 'Handshake', path: 'Hand%20gestures/Handshake.png' },
    { char: '🙏', name: 'Folded Hands', path: 'Hand%20gestures/Folded%20Hands.png' },
    { char: '💪', name: 'Flexed Biceps', path: 'Hand%20gestures/Flexed%20Biceps.png' },
  ],
  'หัวใจ': [
    { char: '❤️', name: 'Red Heart', path: 'Smilies/Red%20Heart.png' },
    { char: '🧡', name: 'Orange Heart', path: 'Smilies/Orange%20Heart.png' },
    { char: '💛', name: 'Yellow Heart', path: 'Smilies/Yellow%20Heart.png' },
    { char: '💚', name: 'Green Heart', path: 'Smilies/Green%20Heart.png' },
    { char: '💙', name: 'Blue Heart', path: 'Smilies/Blue%20Heart.png' },
    { char: '💜', name: 'Purple Heart', path: 'Smilies/Purple%20Heart.png' },
    { char: '🖤', name: 'Black Heart', path: 'Smilies/Black%20Heart.png' },
    { char: '🤍', name: 'White Heart', path: 'Smilies/White%20Heart.png' },
    { char: '🤎', name: 'Brown Heart', path: 'Smilies/Brown%20Heart.png' },
    { char: '💔', name: 'Broken Heart', path: 'Smilies/Broken%20Heart.png' },
    { char: '❣️', name: 'Heart Exclamation', path: 'Smilies/Heart%20Exclamation.png' },
    { char: '💕', name: 'Two Hearts', path: 'Smilies/Two%20Hearts.png' },
    { char: '💞', name: 'Revolving Hearts', path: 'Smilies/Revolving%20Hearts.png' },
    { char: '💓', name: 'Beating Heart', path: 'Smilies/Beating%20Heart.png' },
    { char: '💗', name: 'Growing Heart', path: 'Smilies/Growing%20Heart.png' },
    { char: '💖', name: 'Sparkling Heart', path: 'Smilies/Sparkling%20Heart.png' },
    { char: '💘', name: 'Heart With Arrow', path: 'Smilies/Heart%20with%20Arrow.png' },
    { char: '💝', name: 'Heart With Ribbon', path: 'Smilies/Heart%20with%20Ribbon.png' },
    { char: '💟', name: 'Heart Decoration', path: 'Smilies/Heart%20Decoration.png' },
  ],
  'ธรรมชาติ': [
    { char: '🔥', name: 'Fire', path: 'Travel%20and%20places/Fire.png' },
    { char: '✨', name: 'Sparkles', path: 'Activities/Sparkles.png' },
    { char: '⭐', name: 'Star', path: 'Travel%20and%20places/Star.png' },
    { char: '🌟', name: 'Glowing Star', path: 'Travel%20and%20places/Glowing%20Star.png' },
    { char: '💫', name: 'Dizzy', path: 'Smilies/Dizzy.png' },
    { char: '🌈', name: 'Rainbow', path: 'Travel%20and%20places/Rainbow.png' },
    { char: '☀️', name: 'Sun', path: 'Travel%20and%20places/Sun.png' },
    { char: '🌙', name: 'Crescent Moon', path: 'Travel%20and%20places/Crescent%20Moon.png' },
    { char: '⚡', name: 'High Voltage', path: 'Travel%20and%20places/High%20Voltage.png' },
    { char: '❄️', name: 'Snowflake', path: 'Travel%20and%20places/Snowflake.png' },
    { char: '🌊', name: 'Water Wave', path: 'Travel%20and%20places/Water%20Wave.png' },
    { char: '🌸', name: 'Cherry Blossom', path: 'Animals/Cherry%20Blossom.png' },
    { char: '🌺', name: 'Hibiscus', path: 'Animals/Hibiscus.png' },
    { char: '🌻', name: 'Sunflower', path: 'Animals/Sunflower.png' },
    { char: '🌹', name: 'Rose', path: 'Animals/Rose.png' },
    { char: '🌷', name: 'Tulip', path: 'Animals/Tulip.png' },
    { char: '💐', name: 'Bouquet', path: 'Animals/Bouquet.png' },
    { char: '🐱', name: 'Cat Face', path: 'Animals/Cat%20Face.png' },
    { char: '🐶', name: 'Dog Face', path: 'Animals/Dog%20Face.png' },
    { char: '🦊', name: 'Fox', path: 'Animals/Fox.png' },
    { char: '🦉', name: 'Owl', path: 'Animals/Owl.png' },
    { char: '🦄', name: 'Unicorn', path: 'Animals/Unicorn.png' },
    { char: '🦋', name: 'Butterfly', path: 'Animals/Butterfly.png' },
    { char: '🐝', name: 'Honeybee', path: 'Animals/Honeybee.png' },
  ],
  'อาหาร': [
    { char: '🍎', name: 'Red Apple', path: 'Food/Red%20Apple.png' },
    { char: '🍊', name: 'Tangerine', path: 'Food/Tangerine.png' },
    { char: '🍋', name: 'Lemon', path: 'Food/Lemon.png' },
    { char: '🍇', name: 'Grapes', path: 'Food/Grapes.png' },
    { char: '🍓', name: 'Strawberry', path: 'Food/Strawberry.png' },
    { char: '🍔', name: 'Hamburger', path: 'Food/Hamburger.png' },
    { char: '🍕', name: 'Pizza', path: 'Food/Pizza.png' },
    { char: '🌭', name: 'Hot Dog', path: 'Food/Hot%20Dog.png' },
    { char: '🥪', name: 'Sandwich', path: 'Food/Sandwich.png' },
    { char: '🌮', name: 'Taco', path: 'Food/Taco.png' },
    { char: '🍜', name: 'Steaming Bowl', path: 'Food/Steaming%20Bowl.png' },
    { char: '🍝', name: 'Spaghetti', path: 'Food/Spaghetti.png' },
    { char: '🍣', name: 'Sushi', path: 'Food/Sushi.png' },
    { char: '🍦', name: 'Soft Ice Cream', path: 'Food/Soft%20Ice%20Cream.png' },
    { char: '🍰', name: 'Shortcake', path: 'Food/Shortcake.png' },
    { char: '🍪', name: 'Cookie', path: 'Food/Cookie.png' },
    { char: '🍫', name: 'Chocolate Bar', path: 'Food/Chocolate%20Bar.png' },
    { char: '🍿', name: 'Popcorn', path: 'Food/Popcorn.png' },
    { char: '☕', name: 'Hot Beverage', path: 'Food/Hot%20Beverage.png' },
    { char: '🍺', name: 'Clinking Beer Mugs', path: 'Food/Clinking%20Beer%20Mugs.png' },
    { char: '🧋', name: 'Bubble Tea', path: 'Food/Bubble%20Tea.png' },
    { char: '🍷', name: 'Wine Glass', path: 'Food/Wine%20Glass.png' },
    { char: '🥂', name: 'Clinking Glasses', path: 'Food/Clinking%20Glasses.png' },
    { char: '🍹', name: 'Tropical Drink', path: 'Food/Tropical%20Drink.png' },
  ],
  'กิจกรรม': [
    { char: '🎉', name: 'Party Popper', path: 'Activities/Party%20Popper.png' },
    { char: '🎊', name: 'Confetti Ball', path: 'Activities/Confetti%20Ball.png' },
    { char: '🎈', name: 'Balloon', path: 'Activities/Balloon.png' },
    { char: '🎂', name: 'Birthday Cake', path: 'Food/Birthday%20Cake.png' },
    { char: '🎁', name: 'Wrapped Gift', path: 'Activities/Wrapped%20Gift.png' },
    { char: '🎄', name: 'Christmas Tree', path: 'Activities/Christmas%20Tree.png' },
    { char: '🎃', name: 'Jack O Lantern', path: 'Activities/Jack-O-Lantern.png' },
    { char: '🎆', name: 'Fireworks', path: 'Activities/Fireworks.png' },
    { char: '🎇', name: 'Sparkler', path: 'Activities/Sparkler.png' },
    { char: '🎨', name: 'Artist Palette', path: 'Activities/Artist%20Palette.png' },
    { char: '🎮', name: 'Video Game', path: 'Activities/Video%20Game.png' },
    { char: '🎯', name: 'Direct Hit', path: 'Activities/Bullseye.png' },
    { char: '🏆', name: 'Trophy', path: 'Activities/Trophy.png' },
    { char: '🥇', name: '1st Place Medal', path: 'Activities/1st%20Place%20Medal.png' },
    { char: '⚽', name: 'Soccer Ball', path: 'Activities/Soccer%20Ball.png' },
    { char: '🏀', name: 'Basketball', path: 'Activities/Basketball.png' },
    { char: '🎵', name: 'Musical Note', path: 'Objects/Musical%20Note.png' },
    { char: '🎶', name: 'Musical Notes', path: 'Objects/Musical%20Notes.png' },
    { char: '🎤', name: 'Microphone', path: 'Objects/Microphone.png' },
    { char: '🎸', name: 'Guitar', path: 'Objects/Guitar.png' },
    { char: '🪕', name: 'Banjo', path: 'Objects/Banjo.png' },
    { char: '🎲', name: 'Game Die', path: 'Activities/Game%20Die.png' },
    { char: '🧩', name: 'Puzzle Piece', path: 'Activities/Puzzle%20Piece.png' },
    { char: '✈️', name: 'Airplane', path: 'Travel%20and%20places/Airplane.png' },
  ],
  'สัญลักษณ์': [
    { char: '✅', name: 'Check Mark Button', path: 'Symbols/Check%20Mark%20Button.png' },
    { char: '❌', name: 'Cross Mark', path: 'Symbols/Cross%20Mark.png' },
    { char: '❎', name: 'Cross Mark Button', path: 'Symbols/Cross%20Mark%20Button.png' },
    { char: '💯', name: 'Hundred Points', path: 'Smilies/Hundred%20Points.png' },
    { char: '🔔', name: 'Bell', path: 'Objects/Bell.png' },
    { char: '🔕', name: 'Bell With Slash', path: 'Objects/Bell%20with%20Slash.png' },
    { char: '📢', name: 'Loudspeaker', path: 'Objects/Loudspeaker.png' },
    { char: '💬', name: 'Speech Balloon', path: 'Smilies/Speech%20Balloon.png' },
    { char: '💭', name: 'Thought Balloon', path: 'Smilies/Thought%20Balloon.png' },
    { char: '⏰', name: 'Alarm Clock', path: 'Travel%20and%20places/Alarm%20Clock.png' },
    { char: '💡', name: 'Light Bulb', path: 'Objects/Light%20Bulb.png' },
    { char: '📌', name: 'Pushpin', path: 'Objects/Pushpin.png' },
    { char: '📍', name: 'Round Pushpin', path: 'Objects/Round%20Pushpin.png' },
    { char: '🚀', name: 'Rocket', path: 'Travel%20and%20places/Rocket.png' },
    { char: '🛸', name: 'Flying Saucer', path: 'Travel%20and%20places/Flying%20Saucer.png' },
    { char: '🌍', name: 'Globe Showing Europe Africa', path: 'Travel%20and%20places/Globe%20Showing%20Europe-Africa.png' },
    { char: '🌙', name: 'Crescent Moon', path: 'Travel%20and%20places/Crescent%20Moon.png' },
    { char: '⚡', name: 'High Voltage', path: 'Travel%20and%20places/High%20Voltage.png' },
    { char: '💦', name: 'Sweat Droplets', path: 'Smilies/Sweat%20Droplets.png' },
    { char: '💨', name: 'Dashing Away', path: 'Smilies/Dashing%20Away.png' },
    { char: '🕳️', name: 'Hole', path: 'Smilies/Hole.png' },
    { char: '💣', name: 'Bomb', path: 'Smilies/Bomb.png' },
    { char: '💤', name: 'Zzz', path: 'Smilies/Zzz.png' },
    { char: '🎉', name: 'Party Popper', path: 'Activities/Party%20Popper.png' },
  ],
}

export const EMOJI_CATEGORIES = CATEGORIES
export const EMOJI_CATEGORY_NAMES = Object.keys(CATEGORIES)

const ALL_EMOJIS: EmojiItem[] = Object.values(CATEGORIES).flat()
const EMOJI_BY_CHAR = new Map<string, EmojiItem>(ALL_EMOJIS.map((e) => [e.char, e]))

export function emojiUrlFromChar(char: string): string {
  const item = EMOJI_BY_CHAR.get(char)
  if (item) return `${BASE}/${item.path}`
  const info = EMOJI_MAP[char]
  if (info) return `${BASE}/${info.path}`
  return ''
}

export const AVATAR_EMOJIS = ALL_EMOJIS.map((e) => e.char)
