export interface RemoteSfxItem {
  id: string
  name: string
  emoji: string
  color: string
  url: string
  source: string
}

export const SFX_COOLDOWN_MS = 20_000
const SFX_SIGNAL_PREFIX = '\u2063\u2063'
const SFX_ZERO = '\u200b'
const SFX_ONE = '\u200c'

function encodeInvisibleAscii(value: string) {
  return [...value].map((char) => char.charCodeAt(0).toString(2).padStart(8, '0').replaceAll('0', SFX_ZERO).replaceAll('1', SFX_ONE)).join('')
}

function decodeInvisibleAscii(value: string) {
  if (value.length % 8 !== 0) return ''
  let out = ''
  for (let i = 0; i < value.length; i += 8) {
    const byte = value.slice(i, i + 8)
    let bits = ''
    for (const char of byte) {
      if (char === SFX_ZERO) bits += '0'
      else if (char === SFX_ONE) bits += '1'
      else return ''
    }
    out += String.fromCharCode(parseInt(bits, 2))
  }
  return out
}

export function encodeSfxSignal(item: Pick<RemoteSfxItem, 'id'>) {
  return `${SFX_SIGNAL_PREFIX}${encodeInvisibleAscii(item.id)}`
}

export function decodeSfxSignal(content?: string) {
  if (!content?.startsWith(SFX_SIGNAL_PREFIX)) return null
  const id = decodeInvisibleAscii(content.slice(SFX_SIGNAL_PREFIX.length))
  if (!id) return null
  return findRemoteSfx(id) ?? null
}

export const REMOTE_SFX: RemoteSfxItem[] = [
  {
    id: 'faaah',
    name: 'Faaah',
    emoji: '🗣️',
    color: '#ef4444',
    url: '/sfx/faaah.mp3',
    source: 'https://www.myinstants.com/en/instant/faaah-63455/',
  },
  {
    id: 'error',
    name: 'Error',
    emoji: '⚠️',
    color: '#f97316',
    url: '/sfx/error.mp3',
    source: 'https://www.myinstants.com/en/instant/error-soundss-25534/',
  },
  {
    id: 'baby-laugh',
    name: 'Baby Laugh',
    emoji: '👶',
    color: '#ec4899',
    url: '/sfx/baby-laugh.mp3',
    source: 'https://www.myinstants.com/en/instant/baby-laughing-meme-56428/',
  },
  {
    id: 'outro-song',
    name: 'Outro Song',
    emoji: '🎵',
    color: '#8b5cf6',
    url: '/sfx/outro-song.mp3',
    source: 'https://www.myinstants.com/en/instant/outro-song-77850/',
  },
  {
    id: 'minecraft-oof',
    name: 'Minecraft Oof',
    emoji: '🧱',
    color: '#22c55e',
    url: '/sfx/minecraft-oof.mp3',
    source: 'https://www.myinstants.com/en/instant/oof-minecraft-61039/',
  },
  {
    id: 'minecraft-door',
    name: 'MC Door',
    emoji: '🚪',
    color: '#a16207',
    url: '/sfx/minecraft-door.mp3',
    source: 'https://www.myinstants.com/en/instant/minecraft-door-meme-78947/',
  },
  {
    id: 'helicopter',
    name: 'Helicopter',
    emoji: '🚁',
    color: '#06b6d4',
    url: '/sfx/helicopter.mp3',
    source: 'https://www.myinstants.com/en/instant/helicopter-meme-80475/',
  },
  {
    id: 'sacred',
    name: 'สิ่งศักดิ์สิทธิ์',
    emoji: '🙏',
    color: '#eab308',
    url: '/sfx/sacred.mp3',
    source: 'https://www.myinstants.com/en/instant/singsakdisiththi-1158/',
  },
  {
    id: 'revenge',
    name: 'กูแค้น',
    emoji: '😤',
    color: '#dc2626',
    url: '/sfx/revenge.mp3',
    source: 'https://www.myinstants.com/en/instant/kuuaekhn-47525/',
  },
  {
    id: 'sorry-bro',
    name: 'ผมขอโทษครับพี่',
    emoji: '😅',
    color: '#64748b',
    url: '/sfx/sorry-bro.mp3',
    source: 'https://www.myinstants.com/en/instant/phmkh-othskhrabphii-55011/',
  },
  {
    id: 'what',
    name: 'วอทซ์',
    emoji: '🤨',
    color: '#14b8a6',
    url: '/sfx/what.mp3',
    source: 'https://www.myinstants.com/en/instant/w-thch-90812/',
  },
  {
    id: 'victory',
    name: 'Victory Royale',
    emoji: '🏆',
    color: '#f59e0b',
    url: '/sfx/victory.mp3',
    source: 'Fortnite / PUBG',
  },
  {
    id: '2-tlktbmuk-2-4985',
    name: '2_ตลกตบมุก_2',
    emoji: '🔊',
    color: '#ef4444',
    url: '/sfx/2-tlktbmuk-2-4985.mp3',
    source: 'myinstants',
  },
  {
    id: 'fahhhhhhhhhhhhhh-3525',
    name: 'FAHHHHHHHHHHHHHH',
    emoji: '🔊',
    color: '#f97316',
    url: '/sfx/fahhhhhhhhhhhhhh-3525.mp3',
    source: 'myinstants',
  },
  {
    id: 'vine-boom-sound-70972',
    name: 'VINE BOOM SOUND',
    emoji: '🔊',
    color: '#eab308',
    url: '/sfx/vine-boom-sound-70972.mp3',
    source: 'myinstants',
  },
  {
    id: 'diitebtaaethset-r-75342',
    name: 'อดีตเบต้าเทสเตอร์',
    emoji: '🔊',
    color: '#22c55e',
    url: '/sfx/diitebtaaethset-r-75342.mp3',
    source: 'myinstants',
  },
  {
    id: 'esiiyngnaakh-m-w-92941',
    name: 'เสียงน้าค้อม =w=',
    emoji: '🔊',
    color: '#14b8a6',
    url: '/sfx/esiiyngnaakh-m-w-92941.mp3',
    source: 'myinstants',
  },
  {
    id: 'rizz-sound-effect-54189',
    name: 'rizz sound effect',
    emoji: '🔊',
    color: '#0ea5e9',
    url: '/sfx/rizz-sound-effect-54189.mp3',
    source: 'myinstants',
  },
  {
    id: 'aimaihwaelw-95567',
    name: 'ไม่ไหวแล้ว',
    emoji: '🔊',
    color: '#6366f1',
    url: '/sfx/aimaihwaelw-95567.mp3',
    source: 'myinstants',
  },
  {
    id: 'among-us-role-reveal-sound-34956',
    name: 'Among Us role reveal sound',
    emoji: '🔊',
    color: '#a855f7',
    url: '/sfx/among-us-role-reveal-sound-34956.mp3',
    source: 'myinstants',
  },
  {
    id: 'ack-87763',
    name: 'ACK',
    emoji: '🔊',
    color: '#ec4899',
    url: '/sfx/ack-87763.mp3',
    source: 'myinstants',
  },
  {
    id: 'anime-wow',
    name: 'Anime Wow',
    emoji: '🔊',
    color: '#f43f5e',
    url: '/sfx/anime-wow.mp3',
    source: 'myinstants',
  },
  {
    id: 'sngsay-31492',
    name: 'สงสัย',
    emoji: '🔊',
    color: '#f59e0b',
    url: '/sfx/sngsay-31492.mp3',
    source: 'myinstants',
  },
  {
    id: 'esiiyngnaakh-m-w-4-16142',
    name: 'เสียงน้าค้อม =w= 4',
    emoji: '🔊',
    color: '#78716c',
    url: '/sfx/esiiyngnaakh-m-w-4-16142.mp3',
    source: 'myinstants',
  },
  {
    id: 'tununuuuu-67224',
    name: 'Tununuuuu',
    emoji: '🔊',
    color: '#10b981',
    url: '/sfx/tununuuuu-67224.mp3',
    source: 'myinstants',
  },
  {
    id: 'spiderman-meme-song-37638',
    name: 'spiderman meme song',
    emoji: '🔊',
    color: '#38bdf8',
    url: '/sfx/spiderman-meme-song-37638.mp3',
    source: 'myinstants',
  },
  {
    id: 'wing-27818',
    name: 'วิ้ง',
    emoji: '🔊',
    color: '#e879f9',
    url: '/sfx/wing-27818.mp3',
    source: 'myinstants',
  },
  {
    id: 'thuukt-ng-83135',
    name: 'ถูกต้อง',
    emoji: '🔊',
    color: '#f97316',
    url: '/sfx/thuukt-ng-83135.mp3',
    source: 'myinstants',
  },
  {
    id: 'shocked-sound-37548',
    name: 'Shocked sound',
    emoji: '🔊',
    color: '#eab308',
    url: '/sfx/shocked-sound-37548.mp3',
    source: 'myinstants',
  },
  {
    id: 'fart',
    name: 'Fart',
    emoji: '🔊',
    color: '#84cc16',
    url: '/sfx/fart.mp3',
    source: 'myinstants',
  },
  {
    id: 'wuued-luuen-5465',
    name: 'วื๊ด ลื่น',
    emoji: '🔊',
    color: '#22c55e',
    url: '/sfx/wuued-luuen-5465.mp3',
    source: 'myinstants',
  },
  {
    id: 'bone-crack-23901',
    name: 'Bone Crack',
    emoji: '🔊',
    color: '#14b8a6',
    url: '/sfx/bone-crack-23901.mp3',
    source: 'myinstants',
  },
  {
    id: 'phmkh-othskhrabphii-55011',
    name: 'ผมขอโทษครับพี่',
    emoji: '🔊',
    color: '#0ea5e9',
    url: '/sfx/phmkh-othskhrabphii-55011.mp3',
    source: 'myinstants',
  },
  {
    id: 'dexter-meme-26140',
    name: 'Dexter meme',
    emoji: '🔊',
    color: '#6366f1',
    url: '/sfx/dexter-meme-26140.mp3',
    source: 'myinstants',
  },
  {
    id: 'error-soundss-25534',
    name: 'Error SOUNDSS',
    emoji: '🔊',
    color: '#a855f7',
    url: '/sfx/error-soundss-25534.mp3',
    source: 'myinstants',
  },
  {
    id: 'singsakdisiththi-1158',
    name: 'สิ่งศักดิ์สิทธิ์ๆๆๆๆ',
    emoji: '🔊',
    color: '#ec4899',
    url: '/sfx/singsakdisiththi-1158.mp3',
    source: 'myinstants',
  },
  {
    id: 'dukdik-13562',
    name: 'ดุ๊กดิ๊ก',
    emoji: '🔊',
    color: '#f43f5e',
    url: '/sfx/dukdik-13562.mp3',
    source: 'myinstants',
  },
  {
    id: 'cchae-tawe-ng-34216',
    name: 'จ๊ะเอ๋ตัวเอง',
    emoji: '🔊',
    color: '#f59e0b',
    url: '/sfx/cchae-tawe-ng-34216.mp3',
    source: 'myinstants',
  },
  {
    id: 'ebrkhmuk-74707',
    name: 'เบรคมุก',
    emoji: '🔊',
    color: '#78716c',
    url: '/sfx/ebrkhmuk-74707.mp3',
    source: 'myinstants',
  },
  {
    id: 'indian-song-26519',
    name: 'indian song',
    emoji: '🔊',
    color: '#10b981',
    url: '/sfx/indian-song-26519.mp3',
    source: 'myinstants',
  },
  {
    id: 'tuengopa-471',
    name: 'ตึงโป๊ะๆ',
    emoji: '🔊',
    color: '#38bdf8',
    url: '/sfx/tuengopa-471.mp3',
    source: 'myinstants',
  },
  {
    id: 'anime-ahh-73606',
    name: 'anime ahh',
    emoji: '🔊',
    color: '#e879f9',
    url: '/sfx/anime-ahh-73606.mp3',
    source: 'myinstants',
  },
  {
    id: 'fahhh-42300',
    name: 'Fahhh',
    emoji: '🔊',
    color: '#ef4444',
    url: '/sfx/fahhh-42300.mp3',
    source: 'myinstants',
  },
  {
    id: 'huh-ceeday-65118',
    name: 'Huh? Ceeday',
    emoji: '🔊',
    color: '#f97316',
    url: '/sfx/huh-ceeday-65118.mp3',
    source: 'myinstants',
  },
  {
    id: 'eh-eh-ehhhh-30930',
    name: 'eh?eh?ehhhh?',
    emoji: '🔊',
    color: '#eab308',
    url: '/sfx/eh-eh-ehhhh-30930.mp3',
    source: 'myinstants',
  },
  {
    id: 'chicken-on-tree-screaming-53890',
    name: 'Chicken on tree screaming',
    emoji: '🔊',
    color: '#84cc16',
    url: '/sfx/chicken-on-tree-screaming-53890.mp3',
    source: 'myinstants',
  },
  {
    id: '7-11-hello-welcome-33308',
    name: '7 11 Hello Welcome 33308',
    emoji: '🔊',
    color: '',
    url: '/sfx/7-11-hello-welcome-33308.mp3',
    source: 'myinstants',
  },
  {
    id: '7-eleven-thailand-27718',
    name: '7 Eleven Thailand 27718',
    emoji: '🔊',
    color: '#ef4444',
    url: '/sfx/7-eleven-thailand-27718.mp3',
    source: 'myinstants',
  },
  {
    id: 'a1-thai-1648',
    name: 'A1 Thai 1648',
    emoji: '🔊',
    color: '#f97316',
    url: '/sfx/a1-thai-1648.mp3',
    source: 'myinstants',
  },
  {
    id: 'aeycchang-yango-m-aimmiiephlng-61114',
    name: 'Aeycchang Yango M Aimmiiephlng 61114',
    emoji: '🔊',
    color: '#f59e0b',
    url: '/sfx/aeycchang-yango-m-aimmiiephlng-61114.mp3',
    source: 'myinstants',
  },
  {
    id: 'aikklm-38190',
    name: 'Aikklm 38190',
    emoji: '🔊',
    color: '#eab308',
    url: '/sfx/aikklm-38190.mp3',
    source: 'myinstants',
  },
  {
    id: 'aithy-number-you-dialed-does-not-exist-84251',
    name: 'Aithy Number You Dialed Does Not Exist 84251',
    emoji: '🔊',
    color: '#84cc16',
    url: '/sfx/aithy-number-you-dialed-does-not-exist-84251.mp3',
    source: 'myinstants',
  },
  {
    id: 'biboo-thai-rage-25577',
    name: 'Biboo Thai Rage 25577',
    emoji: '🔊',
    color: '#22c55e',
    url: '/sfx/biboo-thai-rage-25577.mp3',
    source: 'myinstants',
  },
  {
    id: 'black-out-83454',
    name: 'Black Out 83454',
    emoji: '🔊',
    color: '#10b981',
    url: '/sfx/black-out-83454.mp3',
    source: 'myinstants',
  },
  {
    id: 'cht-marke-thailand-37820',
    name: 'Cht Marke Thailand 37820',
    emoji: '🔊',
    color: '#14b8a6',
    url: '/sfx/cht-marke-thailand-37820.mp3',
    source: 'myinstants',
  },
  {
    id: 'dan-hot-thailand-82961',
    name: 'Dan Hot Thailand 82961',
    emoji: '🔊',
    color: '#06b6d4',
    url: '/sfx/dan-hot-thailand-82961.mp3',
    source: 'myinstants',
  },
  {
    id: 'dei-rage-guys',
    name: 'Dei Rage Guys',
    emoji: '🔊',
    color: '#0ea5e9',
    url: '/sfx/dei-rage-guys.mp3',
    source: 'myinstants',
  },
  {
    id: 'drain-gang-tag-71928',
    name: 'Drain Gang Tag 71928',
    emoji: '🔊',
    color: '#3b82f6',
    url: '/sfx/drain-gang-tag-71928.mp3',
    source: 'myinstants',
  },
  {
    id: 'epidtawkhaaef-38919',
    name: 'Epidtawkhaaef 38919',
    emoji: '🔊',
    color: '#6366f1',
    url: '/sfx/epidtawkhaaef-38919.mp3',
    source: 'myinstants',
  },
  {
    id: 'eth-e-aahawaicchchanaip-yango-m-84033',
    name: 'Eth E Aahawaicchchanaip Yango M 84033',
    emoji: '🔊',
    color: '#8b5cf6',
    url: '/sfx/eth-e-aahawaicchchanaip-yango-m-84033.mp3',
    source: 'myinstants',
  },
  {
    id: 'eth-emaa-kmaacchaak-party-yango-m-aimmiiephlng-22257',
    name: 'Eth Emaa Kmaacchaak Party Yango M Aimmiiephlng 22257',
    emoji: '🔊',
    color: '#a855f7',
    url: '/sfx/eth-emaa-kmaacchaak-party-yango-m-aimmiiephlng-22257.mp3',
    source: 'myinstants',
  },
  {
    id: 'eth-ophlmaacchaakaihn-yango-m-aimmiiephlng-5831',
    name: 'Eth Ophlmaacchaakaihn Yango M Aimmiiephlng 5831',
    emoji: '🔊',
    color: '#d946ef',
    url: '/sfx/eth-ophlmaacchaakaihn-yango-m-aimmiiephlng-5831.mp3',
    source: 'myinstants',
  },
  {
    id: 'eth-ophlmaacchaakaihn-yango-m-ephlng-10319',
    name: 'Eth Ophlmaacchaakaihn Yango M Ephlng 10319',
    emoji: '🔊',
    color: '#ec4899',
    url: '/sfx/eth-ophlmaacchaakaihn-yango-m-ephlng-10319.mp3',
    source: 'myinstants',
  },
  {
    id: 'funny-thai-song-bgm-89404',
    name: 'Funny Thai Song Bgm 89404',
    emoji: '🔊',
    color: '',
    url: '/sfx/funny-thai-song-bgm-89404.mp3',
    source: 'myinstants',
  },
  {
    id: 'hello-thailand-789',
    name: 'Hello Thailand 789',
    emoji: '🔊',
    color: '#ef4444',
    url: '/sfx/hello-thailand-789.mp3',
    source: 'myinstants',
  },
  {
    id: 'hr-ymaayphiin-nghr-ymaay-3956',
    name: 'Hr Ymaayphiin Nghr Ymaay 3956',
    emoji: '🔊',
    color: '#f97316',
    url: '/sfx/hr-ymaayphiin-nghr-ymaay-3956.mp3',
    source: 'myinstants',
  },
  {
    id: 'i-hate-you-th',
    name: 'I Hate You Th',
    emoji: '🔊',
    color: '#f59e0b',
    url: '/sfx/i-hate-you-th.mp3',
    source: 'myinstants',
  },
  {
    id: 'ilikeubellthai-90462',
    name: 'Ilikeubellthai 90462',
    emoji: '🔊',
    color: '#eab308',
    url: '/sfx/ilikeubellthai-90462.mp3',
    source: 'myinstants',
  },
  {
    id: 'is-do-my-thai-57277',
    name: 'Is Do My Thai 57277',
    emoji: '🔊',
    color: '#84cc16',
    url: '/sfx/is-do-my-thai-57277.mp3',
    source: 'myinstants',
  },
  {
    id: 'koen-thailand-9054',
    name: 'Koen Thailand 9054',
    emoji: '🔊',
    color: '#22c55e',
    url: '/sfx/koen-thailand-9054.mp3',
    source: 'myinstants',
  },
  {
    id: 'lazy-song-thai-wistle-8809',
    name: 'Lazy Song Thai Wistle 8809',
    emoji: '🔊',
    color: '#10b981',
    url: '/sfx/lazy-song-thai-wistle-8809.mp3',
    source: 'myinstants',
  },
  {
    id: 'legal-thais-90874',
    name: 'Legal Thais 90874',
    emoji: '🔊',
    color: '#14b8a6',
    url: '/sfx/legal-thais-90874.mp3',
    source: 'myinstants',
  },
  {
    id: 'lifeweaver-ult-62126',
    name: 'Lifeweaver Ult 62126',
    emoji: '🔊',
    color: '#06b6d4',
    url: '/sfx/lifeweaver-ult-62126.mp3',
    source: 'myinstants',
  },
  {
    id: 'mensagem-da-thais',
    name: 'Mensagem Da Thais',
    emoji: '🔊',
    color: '#0ea5e9',
    url: '/sfx/mensagem-da-thais.mp3',
    source: 'myinstants',
  },
  {
    id: 'motta-thailam-42708',
    name: 'Motta Thailam 42708',
    emoji: '🔊',
    color: '#3b82f6',
    url: '/sfx/motta-thailam-42708.mp3',
    source: 'myinstants',
  },
  {
    id: 'no-have-34042',
    name: 'No Have 34042',
    emoji: '🔊',
    color: '#6366f1',
    url: '/sfx/no-have-34042.mp3',
    source: 'myinstants',
  },
  {
    id: 'nonononononono',
    name: 'Nonononononono',
    emoji: '🔊',
    color: '#8b5cf6',
    url: '/sfx/nonononononono.mp3',
    source: 'myinstants',
  },
  {
    id: 'oh-wow-n-ngnaphuudaithyaidaelw-34431',
    name: 'Oh Wow N Ngnaphuudaithyaidaelw 34431',
    emoji: '🔊',
    color: '#a855f7',
    url: '/sfx/oh-wow-n-ngnaphuudaithyaidaelw-34431.mp3',
    source: 'myinstants',
  },
  {
    id: 'rrbs-thailandmerah-74787',
    name: 'Rrbs Thailandmerah 74787',
    emoji: '🔊',
    color: '#d946ef',
    url: '/sfx/rrbs-thailandmerah-74787.mp3',
    source: 'myinstants',
  },
  {
    id: 'sepan-77417',
    name: 'Sepan 77417',
    emoji: '🔊',
    color: '#ec4899',
    url: '/sfx/sepan-77417.mp3',
    source: 'myinstants',
  },
  {
    id: 'sf2t-thailand-37318',
    name: 'Sf2t Thailand 37318',
    emoji: '🔊',
    color: '',
    url: '/sfx/sf2t-thailand-37318.mp3',
    source: 'myinstants',
  },
  {
    id: 'svhentaibienthai-93148',
    name: 'Svhentaibienthai 93148',
    emoji: '🔊',
    color: '#ef4444',
    url: '/sfx/svhentaibienthai-93148.mp3',
    source: 'myinstants',
  },
  {
    id: 'swyeridechid-pang-62381',
    name: 'Swyeridechid Pang 62381',
    emoji: '🔊',
    color: '#f97316',
    url: '/sfx/swyeridechid-pang-62381.mp3',
    source: 'myinstants',
  },
  {
    id: 'telen-niken-50303',
    name: 'Telen Niken 50303',
    emoji: '🔊',
    color: '#f59e0b',
    url: '/sfx/telen-niken-50303.mp3',
    source: 'myinstants',
  },
  {
    id: 'thai-acent-91051',
    name: 'Thai Acent 91051',
    emoji: '🔊',
    color: '#eab308',
    url: '/sfx/thai-acent-91051.mp3',
    source: 'myinstants',
  },
  {
    id: 'thai-fruit-song-10107',
    name: 'Thai Fruit Song 10107',
    emoji: '🔊',
    color: '#84cc16',
    url: '/sfx/thai-fruit-song-10107.mp3',
    source: 'myinstants',
  },
  {
    id: 'thailandaop-85639',
    name: 'Thailandaop 85639',
    emoji: '🔊',
    color: '#22c55e',
    url: '/sfx/thailandaop-85639.mp3',
    source: 'myinstants',
  },
  {
    id: 'thais-carla-56179',
    name: 'Thais Carla 56179',
    emoji: '🔊',
    color: '#10b981',
    url: '/sfx/thais-carla-56179.mp3',
    source: 'myinstants',
  },
  {
    id: 'thais-dutra',
    name: 'Thais Dutra',
    emoji: '🔊',
    color: '#14b8a6',
    url: '/sfx/thais-dutra.mp3',
    source: 'myinstants',
  },
  {
    id: 'thamaiptham-air-66425',
    name: 'Thamaiptham Air 66425',
    emoji: '🔊',
    color: '#06b6d4',
    url: '/sfx/thamaiptham-air-66425.mp3',
    source: 'myinstants',
  },
  {
    id: 'tiki-thaia-96404',
    name: 'Tiki Thaia 96404',
    emoji: '🔊',
    color: '#0ea5e9',
    url: '/sfx/tiki-thaia-96404.mp3',
    source: 'myinstants',
  },
  {
    id: 'udn-thai-21723',
    name: 'Udn Thai 21723',
    emoji: '🔊',
    color: '#3b82f6',
    url: '/sfx/udn-thai-21723.mp3',
    source: 'myinstants',
  },
  {
    id: 'w-ds-what-66537',
    name: 'W Ds What 66537',
    emoji: '🔊',
    color: '#6366f1',
    url: '/sfx/w-ds-what-66537.mp3',
    source: 'myinstants',
  },
  {
    id: 'which-elgeebeetee-food-item-98196',
    name: 'Which Elgeebeetee Food Item 98196',
    emoji: '🔊',
    color: '#8b5cf6',
    url: '/sfx/which-elgeebeetee-food-item-98196.mp3',
    source: 'myinstants',
  },
  {
    id: 'you-underestimate-my-power-th',
    name: 'You Underestimate My Power Th',
    emoji: '🔊',
    color: '#a855f7',
    url: '/sfx/you-underestimate-my-power-th.mp3',
    source: 'myinstants',
  },
  { id: 'wow-anime-voice-accent-54170', name: 'Wow! (anime voice accent)', emoji: '🔊', color: '#ef4444', url: '/sfx/wow-anime-voice-accent-54170.mp3', source: 'myinstants' },
  { id: 'mafioso-scream-26038', name: '(mafioso) scream', emoji: '🔊', color: '#f97316', url: '/sfx/mafioso-scream-26038.mp3', source: 'myinstants' },
  { id: 'africa-crying-laugh-commercial-44874', name: 'Africa crying laugh commercial', emoji: '🔊', color: '#f59e0b', url: '/sfx/africa-crying-laugh-commercial-44874.mp3', source: 'myinstants' },
  { id: 'angry-birds-laugh-79944', name: 'Angry Birds Laugh', emoji: '🔊', color: '#eab308', url: '/sfx/angry-birds-laugh-79944.mp3', source: 'myinstants' },
  { id: 'angry-roblox-18419', name: 'angry roblox', emoji: '🔊', color: '#84cc16', url: '/sfx/angry-roblox-18419.mp3', source: 'myinstants' },
  { id: 'anime-ara-ara-mommy-41438', name: 'anime ara ara mommy', emoji: '🔊', color: '#22c55e', url: '/sfx/anime-ara-ara-mommy-41438.mp3', source: 'myinstants' },
  { id: 'anime-bruh-62003', name: 'anime bruh', emoji: '🔊', color: '#10b981', url: '/sfx/anime-bruh-62003.mp3', source: 'myinstants' },
  { id: 'anime-girl-voice-16594', name: 'anime girl voice', emoji: '🔊', color: '#14b8a6', url: '/sfx/anime-girl-voice-16594.mp3', source: 'myinstants' },
  { id: 'anime-wow-pewdiepie-28304', name: 'anime wow pewdiepie', emoji: '🔊', color: '#06b6d4', url: '/sfx/anime-wow-pewdiepie-28304.mp3', source: 'myinstants' },
  { id: 'are-you-my-mommy', name: 'Are you my mommy?', emoji: '🔊', color: '#0ea5e9', url: '/sfx/are-you-my-mommy.mp3', source: 'myinstants' },
  { id: 'asian-meme-huh-49043', name: 'asian meme huh?', emoji: '🔊', color: '#3b82f6', url: '/sfx/asian-meme-huh-49043.mp3', source: 'myinstants' },
  { id: 'aye-bruh-you-got-a-phone-call-15767', name: 'aye bruh you got a phone call', emoji: '🔊', color: '#6366f1', url: '/sfx/aye-bruh-you-got-a-phone-call-15767.mp3', source: 'myinstants' },
  { id: 'baby-crying-soun-73371', name: 'baby crying - soun', emoji: '🔊', color: '#8b5cf6', url: '/sfx/baby-crying-soun-73371.mp3', source: 'myinstants' },
  { id: 'baby-crying-phonk-73031', name: 'baby crying phonk', emoji: '🔊', color: '#a855f7', url: '/sfx/baby-crying-phonk-73031.mp3', source: 'myinstants' },
  { id: 'baby-laughing-32465', name: 'Baby laughing', emoji: '🔊', color: '#d946ef', url: '/sfx/baby-laughing-32465.mp3', source: 'myinstants' },
  { id: 'baby-laughing-meme-56428', name: 'baby laughing meme', emoji: '🔊', color: '#ec4899', url: '/sfx/baby-laughing-meme-56428.mp3', source: 'myinstants' },
  { id: 'baby-launghing-bass-boosted-7850', name: 'Baby launghing bass boosted', emoji: '🔊', color: '#f43f5e', url: '/sfx/baby-launghing-bass-boosted-7850.mp3', source: 'myinstants' },
  { id: 'baby-shark-60127', name: 'baby shark', emoji: '🔊', color: '#ef4444', url: '/sfx/baby-shark-60127.mp3', source: 'myinstants' },
  { id: 'bark-fart-38489', name: 'bark&fart', emoji: '🔊', color: '#f97316', url: '/sfx/bark-fart-38489.mp3', source: 'myinstants' },
  { id: 'bing-chilling-with-vine-boom-60518', name: 'Bing Chilling with vine boom', emoji: '🔊', color: '#f59e0b', url: '/sfx/bing-chilling-with-vine-boom-60518.mp3', source: 'myinstants' },
  { id: 'boi-what-the-hell-boi-63354', name: 'Boi what the hell boi', emoji: '🔊', color: '#eab308', url: '/sfx/boi-what-the-hell-boi-63354.mp3', source: 'myinstants' },
  { id: 'bone-crack-meme-29466', name: 'Bone crack meme', emoji: '🔊', color: '#84cc16', url: '/sfx/bone-crack-meme-29466.mp3', source: 'myinstants' },
  { id: 'bone-crack-sound-effect-52136', name: 'bone crack sound effect', emoji: '🔊', color: '#22c55e', url: '/sfx/bone-crack-sound-effect-52136.mp3', source: 'myinstants' },
  { id: 'boom-vine-sound-83051', name: 'boom vine sound', emoji: '🔊', color: '#10b981', url: '/sfx/boom-vine-sound-83051.mp3', source: 'myinstants' },
  { id: 'boy-what-the-hell-boy-26018', name: 'boy what the hell boy', emoji: '🔊', color: '#14b8a6', url: '/sfx/boy-what-the-hell-boy-26018.mp3', source: 'myinstants' },
  { id: 'brain-fart-80647', name: 'brain fart', emoji: '🔊', color: '#06b6d4', url: '/sfx/brain-fart-80647.mp3', source: 'myinstants' },
  { id: 'brain-fart-slowed-64705', name: 'brain fart slowed', emoji: '🔊', color: '#0ea5e9', url: '/sfx/brain-fart-slowed-64705.mp3', source: 'myinstants' },
  { id: 'cat-laugh-meme-1-15761', name: 'cat laugh meme 1', emoji: '🔊', color: '#3b82f6', url: '/sfx/cat-laugh-meme-1-15761.mp3', source: 'myinstants' },
  { id: 'cat-laughing-at-you-17443', name: 'Cat laughing at you', emoji: '🔊', color: '#6366f1', url: '/sfx/cat-laughing-at-you-17443.mp3', source: 'myinstants' },
  { id: 'chinese-guy-talk-with-vine-boom-75946', name: 'chinese guy talk with vine boom', emoji: '🔊', color: '#8b5cf6', url: '/sfx/chinese-guy-talk-with-vine-boom-75946.mp3', source: 'myinstants' },
  { id: 'chipmunk-laugh-62540', name: 'Chipmunk Laugh', emoji: '🔊', color: '#a855f7', url: '/sfx/chipmunk-laugh-62540.mp3', source: 'myinstants' },
  { id: 'cod-zombies-evil-laugh-88852', name: 'COD Zombies Evil Laugh', emoji: '🔊', color: '#d946ef', url: '/sfx/cod-zombies-evil-laugh-88852.mp3', source: 'myinstants' },
  { id: 'cod-zombies-scream-43169', name: 'cod zombies scream', emoji: '🔊', color: '#ec4899', url: '/sfx/cod-zombies-scream-43169.mp3', source: 'myinstants' },
  { id: 'crack-the-whip', name: 'crack the whip', emoji: '🔊', color: '#f43f5e', url: '/sfx/crack-the-whip.mp3', source: 'myinstants' },
  { id: 'crazy-frog-axel-f-fart-remix-61673', name: 'crazy frog - axel f (fart remix)', emoji: '🔊', color: '#ef4444', url: '/sfx/crazy-frog-axel-f-fart-remix-61673.mp3', source: 'myinstants' },
  { id: 'creeper-explosion-minecraft-82866', name: 'creeper explosion minecraft', emoji: '🔊', color: '#f97316', url: '/sfx/creeper-explosion-minecraft-82866.mp3', source: 'myinstants' },
  { id: 'dax-evil-laugh', name: 'Dax evil laugh', emoji: '🔊', color: '#f59e0b', url: '/sfx/dax-evil-laugh.mp3', source: 'myinstants' },
  { id: 'dead-by-daylight-doctor-laugh-', name: 'Dead By Daylight Doctor Laugh', emoji: '🔊', color: '#eab308', url: '/sfx/dead-by-daylight-doctor-laugh-.mp3', source: 'myinstants' },
  { id: 'discord-cat-scream-35076', name: 'discord cat scream', emoji: '🔊', color: '#84cc16', url: '/sfx/discord-cat-scream-35076.mp3', source: 'myinstants' },
  { id: 'distortion-dab-97700', name: 'Distortion dab', emoji: '🔊', color: '#22c55e', url: '/sfx/distortion-dab-97700.mp3', source: 'myinstants' },
  { id: 'dog-laughing-meme-form-tiktok-40641', name: 'Dog laughing meme form TikTok', emoji: '🔊', color: '#10b981', url: '/sfx/dog-laughing-meme-form-tiktok-40641.mp3', source: 'myinstants' },
  { id: 'doodoo-fart-48895', name: 'doodoo fart', emoji: '🔊', color: '#14b8a6', url: '/sfx/doodoo-fart-48895.mp3', source: 'myinstants' },
  { id: 'dramatic-tiktok-63207', name: 'dramatic tiktok', emoji: '🔊', color: '#06b6d4', url: '/sfx/dramatic-tiktok-63207.mp3', source: 'myinstants' },
  { id: 'dry-fart', name: 'dry fart', emoji: '🔊', color: '#0ea5e9', url: '/sfx/dry-fart.mp3', source: 'myinstants' },
  { id: 'ea-sports-rickroll-24118', name: 'Ea sports rickroll', emoji: '🔊', color: '#3b82f6', url: '/sfx/ea-sports-rickroll-24118.mp3', source: 'myinstants' },
  { id: 'erm-what-the-sigma-51754', name: 'erm what the sigma', emoji: '🔊', color: '#6366f1', url: '/sfx/erm-what-the-sigma-51754.mp3', source: 'myinstants' },
  { id: 'fart-2', name: 'fart 2', emoji: '🔊', color: '#8b5cf6', url: '/sfx/fart-2.mp3', source: 'myinstants' },
  { id: 'fart-echo-16344', name: 'fart echo', emoji: '🔊', color: '#a855f7', url: '/sfx/fart-echo-16344.mp3', source: 'myinstants' },
  { id: 'fart-with-extra-reverb-63068', name: 'fart with extra reverb', emoji: '🔊', color: '#d946ef', url: '/sfx/fart-with-extra-reverb-63068.mp3', source: 'myinstants' },
  { id: 'fnaf-2-scream', name: 'fnaf 2 scream', emoji: '🔊', color: '#ec4899', url: '/sfx/fnaf-2-scream.mp3', source: 'myinstants' },
  { id: 'fnaf-freddys-laugh-74464', name: "Fnaf Freddy's laugh", emoji: '🔊', color: '#f43f5e', url: '/sfx/fnaf-freddys-laugh-74464.mp3', source: 'myinstants' },
  { id: 'fnaf-golden-freddy-scream', name: 'FNaF Golden Freddy Scream', emoji: '🔊', color: '#ef4444', url: '/sfx/fnaf-golden-freddy-scream.mp3', source: 'myinstants' },
  { id: 'fortnite-default-dance-bass-bo', name: 'Fortnite default dance bass boost', emoji: '🔊', color: '#f97316', url: '/sfx/fortnite-default-dance-bass-bo.mp3', source: 'myinstants' },
  { id: 'freddy-fazebear-rickroll-63153', name: 'freddy fazebear rickroll', emoji: '🔊', color: '#f59e0b', url: '/sfx/freddy-fazebear-rickroll-63153.mp3', source: 'myinstants' },
  { id: 'funny-laughing-meme-70907', name: 'funny laughing meme', emoji: '🔊', color: '#eab308', url: '/sfx/funny-laughing-meme-70907.mp3', source: 'myinstants' },
  { id: 'gentle-ya-yeet-83805', name: 'Gentle ya yeet.', emoji: '🔊', color: '#84cc16', url: '/sfx/gentle-ya-yeet-83805.mp3', source: 'myinstants' },
  { id: 'ghast-scream-minecraft-38903', name: 'ghast scream minecraft', emoji: '🔊', color: '#22c55e', url: '/sfx/ghast-scream-minecraft-38903.mp3', source: 'myinstants' },
  { id: 'giga-chad-music-77850', name: 'giga chad music', emoji: '🔊', color: '#10b981', url: '/sfx/giga-chad-music-77850.mp3', source: 'myinstants' },
  { id: 'gigachad-theme-music-51945', name: 'gigachad theme music', emoji: '🔊', color: '#14b8a6', url: '/sfx/gigachad-theme-music-51945.mp3', source: 'myinstants' },
  { id: 'gman-skibidi-toilet-or-creeper-27733', name: 'Gman Skibidi toilet or creeper', emoji: '🔊', color: '#06b6d4', url: '/sfx/gman-skibidi-toilet-or-creeper-27733.mp3', source: 'myinstants' },
  { id: 'goofy-laugh-extreme-92267', name: 'Goofy Laugh Extreme', emoji: '🔊', color: '#0ea5e9', url: '/sfx/goofy-laugh-extreme-92267.mp3', source: 'myinstants' },
  { id: 'happy-mask-salesman-laugh', name: 'Happy Mask Salesman Laugh', emoji: '🔊', color: '#3b82f6', url: '/sfx/happy-mask-salesman-laugh.mp3', source: 'myinstants' },
  { id: 'harms-im-your-mommy-now-74597', name: "Harms I'm your mommy now", emoji: '🔊', color: '#6366f1', url: '/sfx/harms-im-your-mommy-now-74597.mp3', source: 'myinstants' },
  { id: 'hello-guys-welcome-back-to-my-minecraft-let-play-89039', name: 'HELLO GUYS welcome back to my minecraft let play', emoji: '🔊', color: '#8b5cf6', url: '/sfx/hello-guys-welcome-back-to-my-minecraft-let-play-89039.mp3', source: 'myinstants' },
  { id: 'hitmarker-boom-79182', name: 'hitmarker boom', emoji: '🔊', color: '#a855f7', url: '/sfx/hitmarker-boom-79182.mp3', source: 'myinstants' },
  { id: 'hitmarker-meme-71673', name: 'hitmarker meme', emoji: '🔊', color: '#d946ef', url: '/sfx/hitmarker-meme-71673.mp3', source: 'myinstants' },
  { id: 'huh-roblox-4923', name: 'huh (roblox)', emoji: '🔊', color: '#ec4899', url: '/sfx/huh-roblox-4923.mp3', source: 'myinstants' },
  { id: 'huh-sound-60515', name: 'huh sound', emoji: '🔊', color: '#f43f5e', url: '/sfx/huh-sound-60515.mp3', source: 'myinstants' },
  { id: 'huh-rblx-se-61272', name: 'huh? rblx SE', emoji: '🔊', color: '#ef4444', url: '/sfx/huh-rblx-se-61272.mp3', source: 'myinstants' },
  { id: 'i-like-my-cheese-drippy-bruh-72672', name: 'i like my cheese drippy bruh', emoji: '🔊', color: '#f97316', url: '/sfx/i-like-my-cheese-drippy-bruh-72672.mp3', source: 'myinstants' },
  { id: 'ihihihihi-hahahaha-starcasm-nyx-yandere-laugh-69398', name: 'IHIHIHIHI HAHAHAHA - Starcasm Nyx Yandere Laugh', emoji: '🔊', color: '#f59e0b', url: '/sfx/ihihihihi-hahahaha-starcasm-nyx-yandere-laugh-69398.mp3', source: 'myinstants' },
  { id: 'instagram-vine-boom-meme-but-more-cuted-85302', name: 'instagram/vine boom meme (but more cuted :)', emoji: '🔊', color: '#eab308', url: '/sfx/instagram-vine-boom-meme-but-more-cuted-85302.mp3', source: 'myinstants' },
  { id: 'joker-laugh', name: 'Joker Laugh', emoji: '🔊', color: '#84cc16', url: '/sfx/joker-laugh.mp3', source: 'myinstants' },
  { id: 'kept-you-waiting-huh', name: 'Kept you waiting huh?', emoji: '🔊', color: '#22c55e', url: '/sfx/kept-you-waiting-huh.mp3', source: 'myinstants' },
  { id: 'kira-laugh', name: 'Kira Laugh', emoji: '🔊', color: '#10b981', url: '/sfx/kira-laugh.mp3', source: 'myinstants' },
  { id: 'laugh-it-up-52649', name: 'Laugh it up', emoji: '🔊', color: '#14b8a6', url: '/sfx/laugh-it-up-52649.mp3', source: 'myinstants' },
  { id: 'laugh-remix-56970', name: 'Laugh remix', emoji: '🔊', color: '#06b6d4', url: '/sfx/laugh-remix-56970.mp3', source: 'myinstants' },
  { id: 'laughing-dog-meme-78821', name: 'Laughing dog meme', emoji: '🔊', color: '#0ea5e9', url: '/sfx/laughing-dog-meme-78821.mp3', source: 'myinstants' },
  { id: 'le-fart-de-simon-67307', name: 'Le fart de Simon', emoji: '🔊', color: '#3b82f6', url: '/sfx/le-fart-de-simon-67307.mp3', source: 'myinstants' },
  { id: 'long-brain-fart-60967', name: 'Long brain fart', emoji: '🔊', color: '#6366f1', url: '/sfx/long-brain-fart-60967.mp3', source: 'myinstants' },
  { id: 'loud-vine-boom-80660', name: 'Loud vine boom', emoji: '🔊', color: '#8b5cf6', url: '/sfx/loud-vine-boom-80660.mp3', source: 'myinstants' },
  { id: 'loud-vine-boom-sound-68391', name: 'loud vine boom sound', emoji: '🔊', color: '#a855f7', url: '/sfx/loud-vine-boom-sound-68391.mp3', source: 'myinstants' },
  { id: 'low-tier-god-meme-with-vine-booms-91438', name: 'low tier god meme with vine booms', emoji: '🔊', color: '#d946ef', url: '/sfx/low-tier-god-meme-with-vine-booms-91438.mp3', source: 'myinstants' },
  { id: 'luisito-crack-idolo-maquina-artista-75340', name: 'luisito crack idolo maquina artista', emoji: '🔊', color: '#ec4899', url: '/sfx/luisito-crack-idolo-maquina-artista-75340.mp3', source: 'myinstants' },
  { id: 'meme-violin-sad-violin-1460', name: 'meme violin (sad violin)', emoji: '🔊', color: '#f43f5e', url: '/sfx/meme-violin-sad-violin-1460.mp3', source: 'myinstants' },
  { id: 'minecraft-creeper-explosion-97329', name: 'minecraft creeper explosion', emoji: '🔊', color: '#ef4444', url: '/sfx/minecraft-creeper-explosion-97329.mp3', source: 'myinstants' },
  { id: 'minecraft-dead-sound-43810', name: 'minecraft dead sound', emoji: '🔊', color: '#f97316', url: '/sfx/minecraft-dead-sound-43810.mp3', source: 'myinstants' },
  { id: 'minecraft-door-meme-78947', name: 'minecraft Door meme', emoji: '🔊', color: '#f59e0b', url: '/sfx/minecraft-door-meme-78947.mp3', source: 'myinstants' },
  { id: 'minecraft-tnt-boom-53383', name: 'Minecraft tnt boom', emoji: '🔊', color: '#eab308', url: '/sfx/minecraft-tnt-boom-53383.mp3', source: 'myinstants' },
  { id: 'mommy-oni-19646', name: 'mommy oni', emoji: '🔊', color: '#84cc16', url: '/sfx/mommy-oni-19646.mp3', source: 'myinstants' },
  { id: 'mommy-its-over-just-for-laughs-11812', name: "Mommy, It's over! - Just for laughs", emoji: '🔊', color: '#22c55e', url: '/sfx/mommy-its-over-just-for-laughs-11812.mp3', source: 'myinstants' },
  { id: 'my-mommy-said-no-more-deltarune-67142', name: 'my mommy said no more deltarune', emoji: '🔊', color: '#10b981', url: '/sfx/my-mommy-said-no-more-deltarune-67142.mp3', source: 'myinstants' },
  { id: 'my-mommy-said-no-more-skibidi-meme-10289', name: 'My mommy said no more skibidi meme', emoji: '🔊', color: '#14b8a6', url: '/sfx/my-mommy-said-no-more-skibidi-meme-10289.mp3', source: 'myinstants' },
  { id: 'my-mommy-said-no-more-skibidi-toilet-45304', name: 'my mommy said no more skibidi toilet', emoji: '🔊', color: '#06b6d4', url: '/sfx/my-mommy-said-no-more-skibidi-toilet-45304.mp3', source: 'myinstants' },
  { id: 'my-mommy-said-no-more-skibidi-toilet-fahhh-4299', name: 'my mommy said no more skibidi toilet FAHHH', emoji: '🔊', color: '#0ea5e9', url: '/sfx/my-mommy-said-no-more-skibidi-toilet-fahhh-4299.mp3', source: 'myinstants' },
  { id: 'my-mommy-said-no-more-skibidi-toilet-part-2-29220', name: 'My mommy said no more skibidi toilet part 2', emoji: '🔊', color: '#3b82f6', url: '/sfx/my-mommy-said-no-more-skibidi-toilet-part-2-29220.mp3', source: 'myinstants' },
  { id: 'my-mommy-says-no-more-skibidi-toilet-30230', name: 'My mommy says no more skibidi toilet', emoji: '🔊', color: '#6366f1', url: '/sfx/my-mommy-says-no-more-skibidi-toilet-30230.mp3', source: 'myinstants' },
  { id: 'neck-crack-53547', name: 'Neck crack', emoji: '🔊', color: '#8b5cf6', url: '/sfx/neck-crack-53547.mp3', source: 'myinstants' },
  { id: 'never-gonna-give-you-up-rickroll-82263', name: 'Never gonna give you up rickroll', emoji: '🔊', color: '#a855f7', url: '/sfx/never-gonna-give-you-up-rickroll-82263.mp3', source: 'myinstants' },
  { id: 'ngakak-laugh-annoying-79255', name: 'Ngakak laugh annoying', emoji: '🔊', color: '#d946ef', url: '/sfx/ngakak-laugh-annoying-79255.mp3', source: 'myinstants' },
  { id: 'oh-my-god-bruh-ah-hell-no-87528', name: 'Oh my god bruh ah hell no', emoji: '🔊', color: '#ec4899', url: '/sfx/oh-my-god-bruh-ah-hell-no-87528.mp3', source: 'myinstants' },
  { id: 'oh-my-god-hell-no-bruh-51827', name: 'oh my god hell no bruh', emoji: '🔊', color: '#f43f5e', url: '/sfx/oh-my-god-hell-no-bruh-51827.mp3', source: 'myinstants' },
  { id: 'oh-no-no-no-laugh-56694', name: 'oh no no no laugh', emoji: '🔊', color: '#ef4444', url: '/sfx/oh-no-no-no-laugh-56694.mp3', source: 'myinstants' },
  { id: 'ok-boomer-64055', name: 'ok boomer', emoji: '🔊', color: '#f97316', url: '/sfx/ok-boomer-64055.mp3', source: 'myinstants' },
  { id: 'omg-bruh-oh-hell-nah-1993', name: 'omg bruh oh hell nah', emoji: '🔊', color: '#f59e0b', url: '/sfx/omg-bruh-oh-hell-nah-1993.mp3', source: 'myinstants' },
  { id: 'paralelepipedo-de-crack-86758', name: 'paralelepípedo de crack', emoji: '🔊', color: '#eab308', url: '/sfx/paralelepipedo-de-crack-86758.mp3', source: 'myinstants' },
  { id: 'peter-griffin-laugh-7405', name: 'peter griffin laugh', emoji: '🔊', color: '#84cc16', url: '/sfx/peter-griffin-laugh-7405.mp3', source: 'myinstants' },
  { id: 'rat-dance-music-93451', name: 'Rat dance Music', emoji: '🔊', color: '#22c55e', url: '/sfx/rat-dance-music-93451.mp3', source: 'myinstants' },
  { id: 'rizzbot-laugh-66507', name: 'Rizzbot laugh', emoji: '🔊', color: '#10b981', url: '/sfx/rizzbot-laugh-66507.mp3', source: 'myinstants' },
  { id: 'roblox-angry-50103', name: 'roblox angry', emoji: '🔊', color: '#14b8a6', url: '/sfx/roblox-angry-50103.mp3', source: 'myinstants' },
  { id: 'roblox-wow-19124', name: 'roblox wow', emoji: '🔊', color: '#06b6d4', url: '/sfx/roblox-wow-19124.mp3', source: 'myinstants' },
  { id: 'sad-meow-song-88771', name: 'sad meow song', emoji: '🔊', color: '#0ea5e9', url: '/sfx/sad-meow-song-88771.mp3', source: 'myinstants' },
  { id: 'scream', name: 'scream', emoji: '🔊', color: '#3b82f6', url: '/sfx/scream.mp3', source: 'myinstants' },
  { id: 'silly-pinoy-laugh-19103', name: 'Silly pinoy laugh', emoji: '🔊', color: '#6366f1', url: '/sfx/silly-pinoy-laugh-19103.mp3', source: 'myinstants' },
  { id: 'skibidi-toilet-or-creeper-84731', name: 'skibidi toilet or creeper', emoji: '🔊', color: '#8b5cf6', url: '/sfx/skibidi-toilet-or-creeper-84731.mp3', source: 'myinstants' },
  { id: 'skibidi-toilet-vs-creeper-93371', name: 'skibidi toilet vs creeper', emoji: '🔊', color: '#a855f7', url: '/sfx/skibidi-toilet-vs-creeper-93371.mp3', source: 'myinstants' },
  { id: 'slow-baby-laugh-87991', name: 'Slow baby laugh', emoji: '🔊', color: '#d946ef', url: '/sfx/slow-baby-laugh-87991.mp3', source: 'myinstants' },
  { id: 'snake-death-scream-67281', name: 'Snake death scream', emoji: '🔊', color: '#ec4899', url: '/sfx/snake-death-scream-67281.mp3', source: 'myinstants' },
  { id: 'social-credit-siren-vine-boom-93222', name: 'Social Credit Siren (Vine boom)', emoji: '🔊', color: '#f43f5e', url: '/sfx/social-credit-siren-vine-boom-93222.mp3', source: 'myinstants' },
  { id: 'sonic-exe-laugh-35210', name: 'Sonic.EXE laugh', emoji: '🔊', color: '#ef4444', url: '/sfx/sonic-exe-laugh-35210.mp3', source: 'myinstants' },
  { id: 'sonic-exe-scream-15479', name: 'Sonic.exe scream', emoji: '🔊', color: '#f97316', url: '/sfx/sonic-exe-scream-15479.mp3', source: 'myinstants' },
  { id: 'sora-kingdom-hearts-huh-35841', name: 'Sora kingdom hearts- huh', emoji: '🔊', color: '#f59e0b', url: '/sfx/sora-kingdom-hearts-huh-35841.mp3', source: 'myinstants' },
  { id: 'soulja-boy-huh-32090', name: 'soulja boy huh', emoji: '🔊', color: '#eab308', url: '/sfx/soulja-boy-huh-32090.mp3', source: 'myinstants' },
  { id: 'spanish-guy-laughing-94108', name: 'Spanish Guy Laughing', emoji: '🔊', color: '#84cc16', url: '/sfx/spanish-guy-laughing-94108.mp3', source: 'myinstants' },
  { id: 'spongebob-sad-song-94002', name: 'spongebob sad song', emoji: '🔊', color: '#22c55e', url: '/sfx/spongebob-sad-song-94002.mp3', source: 'myinstants' },
  { id: 'stop-posting-about-among-us-62106', name: 'stop posting about among us', emoji: '🔊', color: '#10b981', url: '/sfx/stop-posting-about-among-us-62106.mp3', source: 'myinstants' },
  { id: 'stop-posting-about-baller-43450', name: 'STOP posting about BALLER', emoji: '🔊', color: '#14b8a6', url: '/sfx/stop-posting-about-baller-43450.mp3', source: 'myinstants' },
  { id: 'sus-among-us-sound-75911', name: 'sus among us sound', emoji: '🔊', color: '#06b6d4', url: '/sfx/sus-among-us-sound-75911.mp3', source: 'myinstants' },
  { id: 'sus-rock-86232', name: 'sus rock', emoji: '🔊', color: '#0ea5e9', url: '/sfx/sus-rock-86232.mp3', source: 'myinstants' },
  { id: 'the-long-and-winded-road-fart', name: 'The long and winded road fart', emoji: '🔊', color: '#3b82f6', url: '/sfx/the-long-and-winded-road-fart.mp3', source: 'myinstants' },
  { id: 'toilet-creeper-loudest-ever-74431', name: 'toilet creeper loudest ever', emoji: '🔊', color: '#6366f1', url: '/sfx/toilet-creeper-loudest-ever-74431.mp3', source: 'myinstants' },
  { id: 'tom-aaaaaaaaa-scream-63022', name: 'Tom AAAAAAAAA scream', emoji: '🔊', color: '#8b5cf6', url: '/sfx/tom-aaaaaaaaa-scream-63022.mp3', source: 'myinstants' },
  { id: 'trump-he-goes-home-now-to-mommy-86020', name: 'trump he goes home now to mommy', emoji: '🔊', color: '#a855f7', url: '/sfx/trump-he-goes-home-now-to-mommy-86020.mp3', source: 'myinstants' },
  { id: 'uh-huh-this-my-shit-92391', name: 'uh huh this my shit', emoji: '🔊', color: '#d946ef', url: '/sfx/uh-huh-this-my-shit-92391.mp3', source: 'myinstants' },
  { id: 'um-excuse-me-but-what-the-23978', name: 'um excuse me but what the-', emoji: '🔊', color: '#ec4899', url: '/sfx/um-excuse-me-but-what-the-23978.mp3', source: 'myinstants' },
  { id: 'um-what-the-sigma-16612', name: 'Um, what the sigma', emoji: '🔊', color: '#f43f5e', url: '/sfx/um-what-the-sigma-16612.mp3', source: 'myinstants' },
  { id: 'usada-pekora-fork-you-creeper-78575', name: 'Usada Pekora - Fork you creeper!', emoji: '🔊', color: '#ef4444', url: '/sfx/usada-pekora-fork-you-creeper-78575.mp3', source: 'myinstants' },
  { id: 'villager-what-the-hell-83236', name: 'villager what the hell', emoji: '🔊', color: '#f97316', url: '/sfx/villager-what-the-hell-83236.mp3', source: 'myinstants' },
  { id: 'vincent-price-evil-laugh', name: 'Vincent Price Evil Laugh', emoji: '🔊', color: '#f59e0b', url: '/sfx/vincent-price-evil-laugh.mp3', source: 'myinstants' },
  { id: 'vine-boom-bass-boosted-51080', name: 'vine boom (bass boosted)', emoji: '🔊', color: '#eab308', url: '/sfx/vine-boom-bass-boosted-51080.mp3', source: 'myinstants' },
  { id: 'vine-boom-bass-boost-sound-effect-68900', name: 'vine boom bass boost sound effect', emoji: '🔊', color: '#84cc16', url: '/sfx/vine-boom-bass-boost-sound-effect-68900.mp3', source: 'myinstants' },
  { id: 'vine-boom-low-quality-96237', name: 'vine boom low quality', emoji: '🔊', color: '#22c55e', url: '/sfx/vine-boom-low-quality-96237.mp3', source: 'myinstants' },
  { id: 'vine-boom-meme-26832', name: 'vine boom meme', emoji: '🔊', color: '#10b981', url: '/sfx/vine-boom-meme-26832.mp3', source: 'myinstants' },
  { id: 'vine-boom-slow-45658', name: 'vine boom slow', emoji: '🔊', color: '#14b8a6', url: '/sfx/vine-boom-slow-45658.mp3', source: 'myinstants' },
  { id: 'vine-boom-sound-effect-bass-boosted-20365', name: 'vine boom sound effect (bass boosted)', emoji: '🔊', color: '#06b6d4', url: '/sfx/vine-boom-sound-effect-bass-boosted-20365.mp3', source: 'myinstants' },
  { id: 'vine-boom-sound-effect-full-16880', name: 'vine boom sound effect full', emoji: '🔊', color: '#0ea5e9', url: '/sfx/vine-boom-sound-effect-full-16880.mp3', source: 'myinstants' },
  { id: 'vine-boom-sound-meme-28885', name: 'vine boom sound meme', emoji: '🔊', color: '#3b82f6', url: '/sfx/vine-boom-sound-meme-28885.mp3', source: 'myinstants' },
  { id: 'vine-boom-spam-lol-41799', name: 'vine boom spam lol', emoji: '🔊', color: '#6366f1', url: '/sfx/vine-boom-spam-lol-41799.mp3', source: 'myinstants' },
  { id: 'vine-dramatic-surprise-53023', name: 'vine dramatic surprise', emoji: '🔊', color: '#8b5cf6', url: '/sfx/vine-dramatic-surprise-53023.mp3', source: 'myinstants' },
  { id: 'wait-wait-wait-what-the-hell-legend-sound-65445', name: 'Wait wait wait what the hell legend sound', emoji: '🔊', color: '#a855f7', url: '/sfx/wait-wait-wait-what-the-hell-legend-sound-65445.mp3', source: 'myinstants' },
  { id: 'wait-wait-wait-what-the-hell-salamalecum-48848', name: 'Wait wait wait what the hell salamalecum', emoji: '🔊', color: '#d946ef', url: '/sfx/wait-wait-wait-what-the-hell-salamalecum-48848.mp3', source: 'myinstants' },
  { id: 'wake-up-mommy-i-just-pissed-the-bed-36488', name: 'Wake up mommy i just pissed the bed', emoji: '🔊', color: '#ec4899', url: '/sfx/wake-up-mommy-i-just-pissed-the-bed-36488.mp3', source: 'myinstants' },
  { id: 'wallah-creeper-von-spastiking-yt-62269', name: 'wallah creeper von spastiking yt', emoji: '🔊', color: '#f43f5e', url: '/sfx/wallah-creeper-von-spastiking-yt-62269.mp3', source: 'myinstants' },
  { id: 'warzone-armor-crack-73816', name: 'warzone armor crack', emoji: '🔊', color: '#ef4444', url: '/sfx/warzone-armor-crack-73816.mp3', source: 'myinstants' },
  { id: 'wet-fart-11093', name: 'wet fart', emoji: '🔊', color: '#f97316', url: '/sfx/wet-fart-11093.mp3', source: 'myinstants' },
  { id: 'wet-fart-meme-47937', name: 'Wet fart meme', emoji: '🔊', color: '#f59e0b', url: '/sfx/wet-fart-meme-47937.mp3', source: 'myinstants' },
  { id: 'wet-fart-squish-79252', name: 'wet fart squish', emoji: '🔊', color: '#eab308', url: '/sfx/wet-fart-squish-79252.mp3', source: 'myinstants' },
  { id: 'what-the-hell-speed-up-14372', name: 'what the hell (speed up)', emoji: '🔊', color: '#84cc16', url: '/sfx/what-the-hell-speed-up-14372.mp3', source: 'myinstants' },
  { id: 'what-the-hell-goofy-ahh-slv-sounds-49542', name: 'what the hell goofy ahh (slv_sounds)', emoji: '🔊', color: '#22c55e', url: '/sfx/what-the-hell-goofy-ahh-slv-sounds-49542.mp3', source: 'myinstants' },
  { id: 'what-the-hell-oh-my-god-no-way-82624', name: 'what the hell oh my god no way', emoji: '🔊', color: '#10b981', url: '/sfx/what-the-hell-oh-my-god-no-way-82624.mp3', source: 'myinstants' },
  { id: 'whip-crack', name: 'Whip crack', emoji: '🔊', color: '#14b8a6', url: '/sfx/whip-crack.mp3', source: 'myinstants' },
  { id: 'whip-crack-used-in-johnny-test', name: 'whip crack used in johnny test', emoji: '🔊', color: '#06b6d4', url: '/sfx/whip-crack-used-in-johnny-test.mp3', source: 'myinstants' },
  { id: 'why-do-i-hear-boss-music-87609', name: 'Why do I hear boss music', emoji: '🔊', color: '#0ea5e9', url: '/sfx/why-do-i-hear-boss-music-87609.mp3', source: 'myinstants' },
  { id: 'windows-11-error-sound-46671', name: 'Windows 11 error sound', emoji: '🔊', color: '#3b82f6', url: '/sfx/windows-11-error-sound-46671.mp3', source: 'myinstants' },
  { id: 'woah-what-the-hell-13953', name: 'woah what the hell', emoji: '🔊', color: '#6366f1', url: '/sfx/woah-what-the-hell-13953.mp3', source: 'myinstants' },
  { id: 'woody-woodpecker-laugh', name: 'Woody Woodpecker Laugh', emoji: '🔊', color: '#8b5cf6', url: '/sfx/woody-woodpecker-laugh.mp3', source: 'myinstants' },
  { id: 'yeet-but-its-the-good-yeet-469', name: 'YEET but its the good yeet', emoji: '🔊', color: '#a855f7', url: '/sfx/yeet-but-its-the-good-yeet-469.mp3', source: 'myinstants' },
  { id: 'zehahaha-edward-teach-laugh-86', name: 'ZEHAHAHA (Edward Teach laugh)', emoji: '🔊', color: '#d946ef', url: '/sfx/zehahaha-edward-teach-laugh-86.mp3', source: 'myinstants' },
  { id: 'awkward-moment-64361', name: 'Awkward Moment', emoji: '🔊', color: '#ef4444', url: '/sfx/awkward-moment-64361.mp3', source: 'myinstants' },
  { id: 'bing-chilling-44511', name: 'bing chilling', emoji: '🔊', color: '#f97316', url: '/sfx/bing-chilling-44511.mp3', source: 'myinstants' },
  { id: 'boing-boing-99781', name: 'Boing Boing', emoji: '🔊', color: '#f59e0b', url: '/sfx/boing-boing-99781.mp3', source: 'myinstants' },
  { id: 'deltarune-explosion-13037', name: 'Deltarune Explosion', emoji: '🔊', color: '#eab308', url: '/sfx/deltarune-explosion-13037.mp3', source: 'myinstants' },
  { id: 'dolphin-censor', name: 'Dolphin Censor', emoji: '🔊', color: '#84cc16', url: '/sfx/dolphin-censor.mp3', source: 'myinstants' },
  { id: 'doraemoncoak-72723', name: 'DoraemonCoak', emoji: '🔊', color: '#22c55e', url: '/sfx/doraemoncoak-72723.mp3', source: 'myinstants' },
  { id: 'esiiyngnaakh-m-w-9-6338', name: 'เสียงน้าค้อม =w= 9', emoji: '🔊', color: '#10b981', url: '/sfx/esiiyngnaakh-m-w-9-6338.mp3', source: 'myinstants' },
  { id: 'fnaf-balloon-boy-hello-12102', name: 'FNAF Balloon Boy Hello', emoji: '🔊', color: '#14b8a6', url: '/sfx/fnaf-balloon-boy-hello-12102.mp3', source: 'myinstants' },
  { id: 'giornos-theme-normal-13768', name: 'Giornos Theme normal', emoji: '🔊', color: '#06b6d4', url: '/sfx/giornos-theme-normal-13768.mp3', source: 'myinstants' },
  { id: 'lungering-93473', name: 'ลุงเริง', emoji: '🔊', color: '#0ea5e9', url: '/sfx/lungering-93473.mp3', source: 'myinstants' },
  { id: 'mamboman-bo-shi-ge-ju-matikanetannhauser-9173', name: 'Mambo曼波 诗歌剧Matikanetannhauser', emoji: '🔊', color: '#3b82f6', url: '/sfx/mamboman-bo-shi-ge-ju-matikanetannhauser-9173.mp3', source: 'myinstants' },
  { id: 'meme-final-91448', name: 'Meme final', emoji: '🔊', color: '#6366f1', url: '/sfx/meme-final-91448.mp3', source: 'myinstants' },
  { id: 'minecraft-explosions-53883', name: 'Minecraft Explosions', emoji: '🔊', color: '#8b5cf6', url: '/sfx/minecraft-explosions-53883.mp3', source: 'myinstants' },
  { id: 'minecraft-level-up-sound', name: 'Minecraft Level Up Sound', emoji: '🔊', color: '#a855f7', url: '/sfx/minecraft-level-up-sound.mp3', source: 'myinstants' },
  { id: 'ohhhhhhh', name: 'OHHHHHHH', emoji: '🔊', color: '#d946ef', url: '/sfx/ohhhhhhh.mp3', source: 'myinstants' },
  { id: 'okhnansaarphaaph-45920', name: 'โคนันสารภาพ', emoji: '🔊', color: '#ec4899', url: '/sfx/okhnansaarphaaph-45920.mp3', source: 'myinstants' },
  { id: 're-zero-return-by-death-51511', name: 'Re:Zero Return by Death', emoji: '🔊', color: '#f43f5e', url: '/sfx/re-zero-return-by-death-51511.mp3', source: 'myinstants' },
  { id: 'ren-noxin-tokanainka-55956', name: '人の心とかないんか?', emoji: '🔊', color: '#ef4444', url: '/sfx/ren-noxin-tokanainka-55956.mp3', source: 'myinstants' },
  { id: 'sad-conan-2206', name: 'sad conan', emoji: '🔊', color: '#f97316', url: '/sfx/sad-conan-2206.mp3', source: 'myinstants' },
  { id: 'smoke-clone-naruto-59408', name: 'Smoke clone naruto', emoji: '🔊', color: '#f59e0b', url: '/sfx/smoke-clone-naruto-59408.mp3', source: 'myinstants' },
  { id: 'spongebob-boowomp-96031', name: 'spongebob boowomp', emoji: '🔊', color: '#eab308', url: '/sfx/spongebob-boowomp-96031.mp3', source: 'myinstants' },
  { id: 'sukuna-domain-theme-55785', name: 'Sukuna domain theme', emoji: '🔊', color: '#84cc16', url: '/sfx/sukuna-domain-theme-55785.mp3', source: 'myinstants' },
  { id: 'sukunas-ryoiki-tenkai-86102', name: 'Sukunas ryoiki tenkai', emoji: '🔊', color: '#22c55e', url: '/sfx/sukunas-ryoiki-tenkai-86102.mp3', source: 'myinstants' },
  { id: 'tada', name: 'TADA', emoji: '🔊', color: '#10b981', url: '/sfx/tada.mp3', source: 'myinstants' },
  { id: 'teleport-sound', name: 'Teleport sound', emoji: '🔊', color: '#14b8a6', url: '/sfx/teleport-sound.mp3', source: 'myinstants' },
  { id: 'tm-opera-on-laugh-uma-musume-pretty-derby-31063', name: 'TM Opera On laugh - uma musume:pretty derby', emoji: '🔊', color: '#06b6d4', url: '/sfx/tm-opera-on-laugh-uma-musume-pretty-derby-31063.mp3', source: 'myinstants' },
  { id: 'to-be-continued-jojo', name: 'To be Continued (jojo)', emoji: '🔊', color: '#0ea5e9', url: '/sfx/to-be-continued-jojo.mp3', source: 'myinstants' },
  { id: 'tuturu', name: 'Tuturu', emoji: '🔊', color: '#3b82f6', url: '/sfx/tuturu.mp3', source: 'myinstants' },
  { id: 'u-una-na-ya-ha-62385', name: 'u-una-na-ya-ha', emoji: '🔊', color: '#6366f1', url: '/sfx/u-una-na-ya-ha-62385.mp3', source: 'myinstants' },
  { id: 'windows-xp-error', name: 'Windows XP Error', emoji: '🔊', color: '#8b5cf6', url: '/sfx/windows-xp-error.mp3', source: 'myinstants' },
  { id: 'wow-matikane-tannhauser-2945', name: 'wow~~~ matikane tannhauser', emoji: '🔊', color: '#a855f7', url: '/sfx/wow-matikane-tannhauser-2945.mp3', source: 'myinstants' },
  { id: 'yamate-kudesai-16901', name: 'Yamate Kudesai', emoji: '🔊', color: '#d946ef', url: '/sfx/yamate-kudesai-16901.mp3', source: 'myinstants' },
  { id: 'ykodntuudaichaihm-9528', name: 'อยกโดนตูดใช่ไหม', emoji: '🔊', color: '#ec4899', url: '/sfx/ykodntuudaichaihm-9528.mp3', source: 'myinstants' },
]

export function findRemoteSfx(id: string) {
  return REMOTE_SFX.find((item) => item.id === id)
}
