export interface RemoteSfxItem {
  id: string
  name: string
  emoji: string
  color: string
  url: string
  source: string
}

export const SFX_COOLDOWN_MS = 60_000
const SFX_SIGNAL_PREFIX = '\u2063\u2063'
const SFX_ZERO = '\u200b'
const SFX_ONE = '\u200c'

function encodeInvisibleAscii(value: string) {
  return [...value].map((char) => char.charCodeAt(0).toString(2).padStart(8, '0').replaceAll('0', SFX_ZERO).replaceAll('1', SFX_ONE)).join('')
}

function decodeInvisibleAscii(value: string) {
  if (value.length % 8 !== 0) return ''
  let out = ''
  for (let i = 0; i < value.length; i += 8) {
    const byte = value.slice(i, i + 8)
    let bits = ''
    for (const char of byte) {
      if (char === SFX_ZERO) bits += '0'
      else if (char === SFX_ONE) bits += '1'
      else return ''
    }
    out += String.fromCharCode(parseInt(bits, 2))
  }
  return out
}

export function encodeSfxSignal(item: Pick<RemoteSfxItem, 'id'>) {
  return `${SFX_SIGNAL_PREFIX}${encodeInvisibleAscii(item.id)}`
}

export function decodeSfxSignal(content?: string) {
  if (!content?.startsWith(SFX_SIGNAL_PREFIX)) return null
  const id = decodeInvisibleAscii(content.slice(SFX_SIGNAL_PREFIX.length))
  if (!id) return null
  return findRemoteSfx(id) ?? null
}

export const REMOTE_SFX: RemoteSfxItem[] = [
  {
    id: 'faaah',
    name: 'Faaah',
    emoji: '🗣️',
    color: '#ef4444',
    url: '/sfx/faaah.mp3',
    source: 'https://www.myinstants.com/en/instant/faaah-63455/',
  },
  {
    id: 'error',
    name: 'Error',
    emoji: '⚠️',
    color: '#f97316',
    url: '/sfx/error.mp3',
    source: 'https://www.myinstants.com/en/instant/error-soundss-25534/',
  },
  {
    id: 'baby-laugh',
    name: 'Baby Laugh',
    emoji: '👶',
    color: '#ec4899',
    url: '/sfx/baby-laugh.mp3',
    source: 'https://www.myinstants.com/en/instant/baby-laughing-meme-56428/',
  },
  {
    id: 'outro-song',
    name: 'Outro Song',
    emoji: '🎵',
    color: '#8b5cf6',
    url: '/sfx/outro-song.mp3',
    source: 'https://www.myinstants.com/en/instant/outro-song-77850/',
  },
  {
    id: 'minecraft-oof',
    name: 'Minecraft Oof',
    emoji: '🧱',
    color: '#22c55e',
    url: '/sfx/minecraft-oof.mp3',
    source: 'https://www.myinstants.com/en/instant/oof-minecraft-61039/',
  },
  {
    id: 'minecraft-door',
    name: 'MC Door',
    emoji: '🚪',
    color: '#a16207',
    url: '/sfx/minecraft-door.mp3',
    source: 'https://www.myinstants.com/en/instant/minecraft-door-meme-78947/',
  },
  {
    id: 'helicopter',
    name: 'Helicopter',
    emoji: '🚁',
    color: '#06b6d4',
    url: '/sfx/helicopter.mp3',
    source: 'https://www.myinstants.com/en/instant/helicopter-meme-80475/',
  },
  {
    id: 'sacred',
    name: 'สิ่งศักดิ์สิทธิ์',
    emoji: '🙏',
    color: '#eab308',
    url: '/sfx/sacred.mp3',
    source: 'https://www.myinstants.com/en/instant/singsakdisiththi-1158/',
  },
  {
    id: 'revenge',
    name: 'กูแค้น',
    emoji: '😤',
    color: '#dc2626',
    url: '/sfx/revenge.mp3',
    source: 'https://www.myinstants.com/en/instant/kuuaekhn-47525/',
  },
  {
    id: 'sorry-bro',
    name: 'ผมขอโทษครับพี่',
    emoji: '😅',
    color: '#64748b',
    url: '/sfx/sorry-bro.mp3',
    source: 'https://www.myinstants.com/en/instant/phmkh-othskhrabphii-55011/',
  },
  {
    id: 'what',
    name: 'วอทซ์',
    emoji: '🤨',
    color: '#14b8a6',
    url: '/sfx/what.mp3',
    source: 'https://www.myinstants.com/en/instant/w-thch-90812/',
  },
  {
    id: 'victory',
    name: 'Victory Royale',
    emoji: '🏆',
    color: '#f59e0b',
    url: '/sfx/victory.mp3',
    source: 'Fortnite / PUBG',
  },
  {
    id: '2-tlktbmuk-2-4985',
    name: '2_ตลกตบมุก_2',
    emoji: '🔊',
    color: '#ef4444',
    url: '/sfx/2-tlktbmuk-2-4985.mp3',
    source: 'myinstants',
  },
  {
    id: 'fahhhhhhhhhhhhhh-3525',
    name: 'FAHHHHHHHHHHHHHH',
    emoji: '🔊',
    color: '#f97316',
    url: '/sfx/fahhhhhhhhhhhhhh-3525.mp3',
    source: 'myinstants',
  },
  {
    id: 'vine-boom-sound-70972',
    name: 'VINE BOOM SOUND',
    emoji: '🔊',
    color: '#eab308',
    url: '/sfx/vine-boom-sound-70972.mp3',
    source: 'myinstants',
  },
  {
    id: 'diitebtaaethset-r-75342',
    name: 'อดีตเบต้าเทสเตอร์',
    emoji: '🔊',
    color: '#22c55e',
    url: '/sfx/diitebtaaethset-r-75342.mp3',
    source: 'myinstants',
  },
  {
    id: 'esiiyngnaakh-m-w-92941',
    name: 'เสียงน้าค้อม =w=',
    emoji: '🔊',
    color: '#14b8a6',
    url: '/sfx/esiiyngnaakh-m-w-92941.mp3',
    source: 'myinstants',
  },
  {
    id: 'rizz-sound-effect-54189',
    name: 'rizz sound effect',
    emoji: '🔊',
    color: '#0ea5e9',
    url: '/sfx/rizz-sound-effect-54189.mp3',
    source: 'myinstants',
  },
  {
    id: 'aimaihwaelw-95567',
    name: 'ไม่ไหวแล้ว',
    emoji: '🔊',
    color: '#6366f1',
    url: '/sfx/aimaihwaelw-95567.mp3',
    source: 'myinstants',
  },
  {
    id: 'among-us-role-reveal-sound-34956',
    name: 'Among Us role reveal sound',
    emoji: '🔊',
    color: '#a855f7',
    url: '/sfx/among-us-role-reveal-sound-34956.mp3',
    source: 'myinstants',
  },
  {
    id: 'ack-87763',
    name: 'ACK',
    emoji: '🔊',
    color: '#ec4899',
    url: '/sfx/ack-87763.mp3',
    source: 'myinstants',
  },
  {
    id: 'anime-wow',
    name: 'Anime Wow',
    emoji: '🔊',
    color: '#f43f5e',
    url: '/sfx/anime-wow.mp3',
    source: 'myinstants',
  },
  {
    id: 'sngsay-31492',
    name: 'สงสัย',
    emoji: '🔊',
    color: '#f59e0b',
    url: '/sfx/sngsay-31492.mp3',
    source: 'myinstants',
  },
  {
    id: 'esiiyngnaakh-m-w-4-16142',
    name: 'เสียงน้าค้อม =w= 4',
    emoji: '🔊',
    color: '#78716c',
    url: '/sfx/esiiyngnaakh-m-w-4-16142.mp3',
    source: 'myinstants',
  },
  {
    id: 'tununuuuu-67224',
    name: 'Tununuuuu',
    emoji: '🔊',
    color: '#10b981',
    url: '/sfx/tununuuuu-67224.mp3',
    source: 'myinstants',
  },
  {
    id: 'spiderman-meme-song-37638',
    name: 'spiderman meme song',
    emoji: '🔊',
    color: '#38bdf8',
    url: '/sfx/spiderman-meme-song-37638.mp3',
    source: 'myinstants',
  },
  {
    id: 'wing-27818',
    name: 'วิ้ง',
    emoji: '🔊',
    color: '#e879f9',
    url: '/sfx/wing-27818.mp3',
    source: 'myinstants',
  },
  {
    id: 'thuukt-ng-83135',
    name: 'ถูกต้อง',
    emoji: '🔊',
    color: '#f97316',
    url: '/sfx/thuukt-ng-83135.mp3',
    source: 'myinstants',
  },
  {
    id: 'shocked-sound-37548',
    name: 'Shocked sound',
    emoji: '🔊',
    color: '#eab308',
    url: '/sfx/shocked-sound-37548.mp3',
    source: 'myinstants',
  },
  {
    id: 'fart',
    name: 'Fart',
    emoji: '🔊',
    color: '#84cc16',
    url: '/sfx/fart.mp3',
    source: 'myinstants',
  },
  {
    id: 'wuued-luuen-5465',
    name: 'วื๊ด ลื่น',
    emoji: '🔊',
    color: '#22c55e',
    url: '/sfx/wuued-luuen-5465.mp3',
    source: 'myinstants',
  },
  {
    id: 'bone-crack-23901',
    name: 'Bone Crack',
    emoji: '🔊',
    color: '#14b8a6',
    url: '/sfx/bone-crack-23901.mp3',
    source: 'myinstants',
  },
  {
    id: 'phmkh-othskhrabphii-55011',
    name: 'ผมขอโทษครับพี่',
    emoji: '🔊',
    color: '#0ea5e9',
    url: '/sfx/phmkh-othskhrabphii-55011.mp3',
    source: 'myinstants',
  },
  {
    id: 'dexter-meme-26140',
    name: 'Dexter meme',
    emoji: '🔊',
    color: '#6366f1',
    url: '/sfx/dexter-meme-26140.mp3',
    source: 'myinstants',
  },
  {
    id: 'error-soundss-25534',
    name: 'Error SOUNDSS',
    emoji: '🔊',
    color: '#a855f7',
    url: '/sfx/error-soundss-25534.mp3',
    source: 'myinstants',
  },
  {
    id: 'singsakdisiththi-1158',
    name: 'สิ่งศักดิ์สิทธิ์ๆๆๆๆ',
    emoji: '🔊',
    color: '#ec4899',
    url: '/sfx/singsakdisiththi-1158.mp3',
    source: 'myinstants',
  },
  {
    id: 'dukdik-13562',
    name: 'ดุ๊กดิ๊ก',
    emoji: '🔊',
    color: '#f43f5e',
    url: '/sfx/dukdik-13562.mp3',
    source: 'myinstants',
  },
  {
    id: 'cchae-tawe-ng-34216',
    name: 'จ๊ะเอ๋ตัวเอง',
    emoji: '🔊',
    color: '#f59e0b',
    url: '/sfx/cchae-tawe-ng-34216.mp3',
    source: 'myinstants',
  },
  {
    id: 'ebrkhmuk-74707',
    name: 'เบรคมุก',
    emoji: '🔊',
    color: '#78716c',
    url: '/sfx/ebrkhmuk-74707.mp3',
    source: 'myinstants',
  },
  {
    id: 'indian-song-26519',
    name: 'indian song',
    emoji: '🔊',
    color: '#10b981',
    url: '/sfx/indian-song-26519.mp3',
    source: 'myinstants',
  },
  {
    id: 'tuengopa-471',
    name: 'ตึงโป๊ะๆ',
    emoji: '🔊',
    color: '#38bdf8',
    url: '/sfx/tuengopa-471.mp3',
    source: 'myinstants',
  },
  {
    id: 'anime-ahh-73606',
    name: 'anime ahh',
    emoji: '🔊',
    color: '#e879f9',
    url: '/sfx/anime-ahh-73606.mp3',
    source: 'myinstants',
  },
  {
    id: 'fahhh-42300',
    name: 'Fahhh',
    emoji: '🔊',
    color: '#ef4444',
    url: '/sfx/fahhh-42300.mp3',
    source: 'myinstants',
  },
  {
    id: 'huh-ceeday-65118',
    name: 'Huh? Ceeday',
    emoji: '🔊',
    color: '#f97316',
    url: '/sfx/huh-ceeday-65118.mp3',
    source: 'myinstants',
  },
  {
    id: 'eh-eh-ehhhh-30930',
    name: 'eh?eh?ehhhh?',
    emoji: '🔊',
    color: '#eab308',
    url: '/sfx/eh-eh-ehhhh-30930.mp3',
    source: 'myinstants',
  },
  {
    id: 'chicken-on-tree-screaming-53890',
    name: 'Chicken on tree screaming',
    emoji: '🔊',
    color: '#84cc16',
    url: '/sfx/chicken-on-tree-screaming-53890.mp3',
    source: 'myinstants',
  },
  {
    id: '7-11-hello-welcome-33308',
    name: '7 11 Hello Welcome 33308',
    emoji: '🔊',
    color: '',
    url: '/sfx/7-11-hello-welcome-33308.mp3',
    source: 'myinstants',
  },
  {
    id: '7-eleven-thailand-27718',
    name: '7 Eleven Thailand 27718',
    emoji: '🔊',
    color: '#ef4444',
    url: '/sfx/7-eleven-thailand-27718.mp3',
    source: 'myinstants',
  },
  {
    id: 'a1-thai-1648',
    name: 'A1 Thai 1648',
    emoji: '🔊',
    color: '#f97316',
    url: '/sfx/a1-thai-1648.mp3',
    source: 'myinstants',
  },
  {
    id: 'aeycchang-yango-m-aimmiiephlng-61114',
    name: 'Aeycchang Yango M Aimmiiephlng 61114',
    emoji: '🔊',
    color: '#f59e0b',
    url: '/sfx/aeycchang-yango-m-aimmiiephlng-61114.mp3',
    source: 'myinstants',
  },
  {
    id: 'aikklm-38190',
    name: 'Aikklm 38190',
    emoji: '🔊',
    color: '#eab308',
    url: '/sfx/aikklm-38190.mp3',
    source: 'myinstants',
  },
  {
    id: 'aithy-number-you-dialed-does-not-exist-84251',
    name: 'Aithy Number You Dialed Does Not Exist 84251',
    emoji: '🔊',
    color: '#84cc16',
    url: '/sfx/aithy-number-you-dialed-does-not-exist-84251.mp3',
    source: 'myinstants',
  },
  {
    id: 'biboo-thai-rage-25577',
    name: 'Biboo Thai Rage 25577',
    emoji: '🔊',
    color: '#22c55e',
    url: '/sfx/biboo-thai-rage-25577.mp3',
    source: 'myinstants',
  },
  {
    id: 'black-out-83454',
    name: 'Black Out 83454',
    emoji: '🔊',
    color: '#10b981',
    url: '/sfx/black-out-83454.mp3',
    source: 'myinstants',
  },
  {
    id: 'cht-marke-thailand-37820',
    name: 'Cht Marke Thailand 37820',
    emoji: '🔊',
    color: '#14b8a6',
    url: '/sfx/cht-marke-thailand-37820.mp3',
    source: 'myinstants',
  },
  {
    id: 'dan-hot-thailand-82961',
    name: 'Dan Hot Thailand 82961',
    emoji: '🔊',
    color: '#06b6d4',
    url: '/sfx/dan-hot-thailand-82961.mp3',
    source: 'myinstants',
  },
  {
    id: 'dei-rage-guys',
    name: 'Dei Rage Guys',
    emoji: '🔊',
    color: '#0ea5e9',
    url: '/sfx/dei-rage-guys.mp3',
    source: 'myinstants',
  },
  {
    id: 'drain-gang-tag-71928',
    name: 'Drain Gang Tag 71928',
    emoji: '🔊',
    color: '#3b82f6',
    url: '/sfx/drain-gang-tag-71928.mp3',
    source: 'myinstants',
  },
  {
    id: 'epidtawkhaaef-38919',
    name: 'Epidtawkhaaef 38919',
    emoji: '🔊',
    color: '#6366f1',
    url: '/sfx/epidtawkhaaef-38919.mp3',
    source: 'myinstants',
  },
  {
    id: 'eth-e-aahawaicchchanaip-yango-m-84033',
    name: 'Eth E Aahawaicchchanaip Yango M 84033',
    emoji: '🔊',
    color: '#8b5cf6',
    url: '/sfx/eth-e-aahawaicchchanaip-yango-m-84033.mp3',
    source: 'myinstants',
  },
  {
    id: 'eth-emaa-kmaacchaak-party-yango-m-aimmiiephlng-22257',
    name: 'Eth Emaa Kmaacchaak Party Yango M Aimmiiephlng 22257',
    emoji: '🔊',
    color: '#a855f7',
    url: '/sfx/eth-emaa-kmaacchaak-party-yango-m-aimmiiephlng-22257.mp3',
    source: 'myinstants',
  },
  {
    id: 'eth-ophlmaacchaakaihn-yango-m-aimmiiephlng-5831',
    name: 'Eth Ophlmaacchaakaihn Yango M Aimmiiephlng 5831',
    emoji: '🔊',
    color: '#d946ef',
    url: '/sfx/eth-ophlmaacchaakaihn-yango-m-aimmiiephlng-5831.mp3',
    source: 'myinstants',
  },
  {
    id: 'eth-ophlmaacchaakaihn-yango-m-ephlng-10319',
    name: 'Eth Ophlmaacchaakaihn Yango M Ephlng 10319',
    emoji: '🔊',
    color: '#ec4899',
    url: '/sfx/eth-ophlmaacchaakaihn-yango-m-ephlng-10319.mp3',
    source: 'myinstants',
  },
  {
    id: 'funny-thai-song-bgm-89404',
    name: 'Funny Thai Song Bgm 89404',
    emoji: '🔊',
    color: '',
    url: '/sfx/funny-thai-song-bgm-89404.mp3',
    source: 'myinstants',
  },
  {
    id: 'hello-thailand-789',
    name: 'Hello Thailand 789',
    emoji: '🔊',
    color: '#ef4444',
    url: '/sfx/hello-thailand-789.mp3',
    source: 'myinstants',
  },
  {
    id: 'hr-ymaayphiin-nghr-ymaay-3956',
    name: 'Hr Ymaayphiin Nghr Ymaay 3956',
    emoji: '🔊',
    color: '#f97316',
    url: '/sfx/hr-ymaayphiin-nghr-ymaay-3956.mp3',
    source: 'myinstants',
  },
  {
    id: 'i-hate-you-th',
    name: 'I Hate You Th',
    emoji: '🔊',
    color: '#f59e0b',
    url: '/sfx/i-hate-you-th.mp3',
    source: 'myinstants',
  },
  {
    id: 'ilikeubellthai-90462',
    name: 'Ilikeubellthai 90462',
    emoji: '🔊',
    color: '#eab308',
    url: '/sfx/ilikeubellthai-90462.mp3',
    source: 'myinstants',
  },
  {
    id: 'is-do-my-thai-57277',
    name: 'Is Do My Thai 57277',
    emoji: '🔊',
    color: '#84cc16',
    url: '/sfx/is-do-my-thai-57277.mp3',
    source: 'myinstants',
  },
  {
    id: 'koen-thailand-9054',
    name: 'Koen Thailand 9054',
    emoji: '🔊',
    color: '#22c55e',
    url: '/sfx/koen-thailand-9054.mp3',
    source: 'myinstants',
  },
  {
    id: 'lazy-song-thai-wistle-8809',
    name: 'Lazy Song Thai Wistle 8809',
    emoji: '🔊',
    color: '#10b981',
    url: '/sfx/lazy-song-thai-wistle-8809.mp3',
    source: 'myinstants',
  },
  {
    id: 'legal-thais-90874',
    name: 'Legal Thais 90874',
    emoji: '🔊',
    color: '#14b8a6',
    url: '/sfx/legal-thais-90874.mp3',
    source: 'myinstants',
  },
  {
    id: 'lifeweaver-ult-62126',
    name: 'Lifeweaver Ult 62126',
    emoji: '🔊',
    color: '#06b6d4',
    url: '/sfx/lifeweaver-ult-62126.mp3',
    source: 'myinstants',
  },
  {
    id: 'mensagem-da-thais',
    name: 'Mensagem Da Thais',
    emoji: '🔊',
    color: '#0ea5e9',
    url: '/sfx/mensagem-da-thais.mp3',
    source: 'myinstants',
  },
  {
    id: 'motta-thailam-42708',
    name: 'Motta Thailam 42708',
    emoji: '🔊',
    color: '#3b82f6',
    url: '/sfx/motta-thailam-42708.mp3',
    source: 'myinstants',
  },
  {
    id: 'no-have-34042',
    name: 'No Have 34042',
    emoji: '🔊',
    color: '#6366f1',
    url: '/sfx/no-have-34042.mp3',
    source: 'myinstants',
  },
  {
    id: 'nonononononono',
    name: 'Nonononononono',
    emoji: '🔊',
    color: '#8b5cf6',
    url: '/sfx/nonononononono.mp3',
    source: 'myinstants',
  },
  {
    id: 'oh-wow-n-ngnaphuudaithyaidaelw-34431',
    name: 'Oh Wow N Ngnaphuudaithyaidaelw 34431',
    emoji: '🔊',
    color: '#a855f7',
    url: '/sfx/oh-wow-n-ngnaphuudaithyaidaelw-34431.mp3',
    source: 'myinstants',
  },
  {
    id: 'rrbs-thailandmerah-74787',
    name: 'Rrbs Thailandmerah 74787',
    emoji: '🔊',
    color: '#d946ef',
    url: '/sfx/rrbs-thailandmerah-74787.mp3',
    source: 'myinstants',
  },
  {
    id: 'sepan-77417',
    name: 'Sepan 77417',
    emoji: '🔊',
    color: '#ec4899',
    url: '/sfx/sepan-77417.mp3',
    source: 'myinstants',
  },
  {
    id: 'sf2t-thailand-37318',
    name: 'Sf2t Thailand 37318',
    emoji: '🔊',
    color: '',
    url: '/sfx/sf2t-thailand-37318.mp3',
    source: 'myinstants',
  },
  {
    id: 'svhentaibienthai-93148',
    name: 'Svhentaibienthai 93148',
    emoji: '🔊',
    color: '#ef4444',
    url: '/sfx/svhentaibienthai-93148.mp3',
    source: 'myinstants',
  },
  {
    id: 'swyeridechid-pang-62381',
    name: 'Swyeridechid Pang 62381',
    emoji: '🔊',
    color: '#f97316',
    url: '/sfx/swyeridechid-pang-62381.mp3',
    source: 'myinstants',
  },
  {
    id: 'telen-niken-50303',
    name: 'Telen Niken 50303',
    emoji: '🔊',
    color: '#f59e0b',
    url: '/sfx/telen-niken-50303.mp3',
    source: 'myinstants',
  },
  {
    id: 'thai-acent-91051',
    name: 'Thai Acent 91051',
    emoji: '🔊',
    color: '#eab308',
    url: '/sfx/thai-acent-91051.mp3',
    source: 'myinstants',
  },
  {
    id: 'thai-fruit-song-10107',
    name: 'Thai Fruit Song 10107',
    emoji: '🔊',
    color: '#84cc16',
    url: '/sfx/thai-fruit-song-10107.mp3',
    source: 'myinstants',
  },
  {
    id: 'thailandaop-85639',
    name: 'Thailandaop 85639',
    emoji: '🔊',
    color: '#22c55e',
    url: '/sfx/thailandaop-85639.mp3',
    source: 'myinstants',
  },
  {
    id: 'thais-carla-56179',
    name: 'Thais Carla 56179',
    emoji: '🔊',
    color: '#10b981',
    url: '/sfx/thais-carla-56179.mp3',
    source: 'myinstants',
  },
  {
    id: 'thais-dutra',
    name: 'Thais Dutra',
    emoji: '🔊',
    color: '#14b8a6',
    url: '/sfx/thais-dutra.mp3',
    source: 'myinstants',
  },
  {
    id: 'thamaiptham-air-66425',
    name: 'Thamaiptham Air 66425',
    emoji: '🔊',
    color: '#06b6d4',
    url: '/sfx/thamaiptham-air-66425.mp3',
    source: 'myinstants',
  },
  {
    id: 'tiki-thaia-96404',
    name: 'Tiki Thaia 96404',
    emoji: '🔊',
    color: '#0ea5e9',
    url: '/sfx/tiki-thaia-96404.mp3',
    source: 'myinstants',
  },
  {
    id: 'udn-thai-21723',
    name: 'Udn Thai 21723',
    emoji: '🔊',
    color: '#3b82f6',
    url: '/sfx/udn-thai-21723.mp3',
    source: 'myinstants',
  },
  {
    id: 'w-ds-what-66537',
    name: 'W Ds What 66537',
    emoji: '🔊',
    color: '#6366f1',
    url: '/sfx/w-ds-what-66537.mp3',
    source: 'myinstants',
  },
  {
    id: 'which-elgeebeetee-food-item-98196',
    name: 'Which Elgeebeetee Food Item 98196',
    emoji: '🔊',
    color: '#8b5cf6',
    url: '/sfx/which-elgeebeetee-food-item-98196.mp3',
    source: 'myinstants',
  },
  {
    id: 'you-underestimate-my-power-th',
    name: 'You Underestimate My Power Th',
    emoji: '🔊',
    color: '#a855f7',
    url: '/sfx/you-underestimate-my-power-th.mp3',
    source: 'myinstants',
  },
]

export function findRemoteSfx(id: string) {
  return REMOTE_SFX.find((item) => item.id === id)
}
